# Generated by Django 5.2.10 on 2026-01-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analytics', '0001_initial'),
        ('learnerships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='learnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learnerships.learnershipprogramme'),
        ),
    ]
