# Generated by Django 5.2.10 on 2026-01-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aicerts_courses', '0001_initial'),
        ('analytics', '0002_initial'),
        ('learnerships', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courseanalytics',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='aicerts_courses.aicertscourse'),
        ),
        migrations.AddField(
            model_name='learnershipanalytics',
            name='learnership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='learnerships.learnershipprogramme'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aicerts_courses.aicertscourse'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='learnership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learnerships.learnershipprogramme'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='courseanalytics',
            unique_together={('course', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='learnershipanalytics',
            unique_together={('learnership', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'course'), ('user', 'learnership')},
        ),
    ]
