# Generated by Django 5.2.10 on 2026-01-24 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_initial'),
        ('industry_based_training', '0001_initial'),
        ('masterclasses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('certificates_issued', models.IntegerField(default=0)),
                ('certificates_expired', models.IntegerField(default=0)),
                ('certificates_renewed', models.IntegerField(default=0)),
                ('active_certifications', models.IntegerField(default=0)),
                ('certificates_masterclass', models.IntegerField(default=0)),
                ('certificates_learnership', models.IntegerField(default=0)),
                ('certificates_industry', models.IntegerField(default=0)),
                ('certificates_aicerts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificate Analytics',
                'verbose_name_plural': 'Certificate Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RevenueAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('gross_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('refunds', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transaction_count', models.IntegerField(default=0)),
                ('failed_transactions', models.IntegerField(default=0)),
                ('avg_transaction_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_masterclass', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_learnership', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_industry_training', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('revenue_aicerts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Revenue Analytics',
                'verbose_name_plural': 'Revenue Analytics',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='avg_session_duration',
            field=models.FloatField(default=0.0, help_text='Average session duration in minutes'),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='certificates_issued',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='completion_rate',
            field=models.FloatField(default=0.0, help_text='Overall completion rate percentage'),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='course_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='daily_active_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='engagement_score',
            field=models.FloatField(default=0.0, help_text='Composite engagement score (0-100)'),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='new_enrollments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='retention_rate',
            field=models.FloatField(default=0.0, help_text='User retention rate percentage'),
        ),
        migrations.AddField(
            model_name='platformanalytics',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='EngagementMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('login_count', models.IntegerField(default=0)),
                ('time_spent_minutes', models.FloatField(default=0.0)),
                ('content_views', models.IntegerField(default=0)),
                ('quiz_attempts', models.IntegerField(default=0)),
                ('discussion_posts', models.IntegerField(default=0)),
                ('resource_downloads', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0, help_text='Calculated composite score (0-100)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Engagement Metrics',
                'verbose_name_plural': 'Engagement Metrics',
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='IndustryTrainingAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course_views', models.IntegerField(default=0)),
                ('enrollments', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='industry_based_training.industry')),
            ],
            options={
                'verbose_name': 'Industry Training Analytics',
                'verbose_name_plural': 'Industry Training Analytics',
                'ordering': ['-date'],
                'unique_together': {('industry', 'date')},
            },
        ),
        migrations.CreateModel(
            name='InstructorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('courses_taught', models.IntegerField(default=0)),
                ('total_students', models.IntegerField(default=0)),
                ('avg_student_rating', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('response_time_hours', models.FloatField(default=0.0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor Analytics',
                'verbose_name_plural': 'Instructor Analytics',
                'ordering': ['-date'],
                'unique_together': {('instructor', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MasterclassAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.IntegerField(default=0)),
                ('enrollments', models.IntegerField(default=0)),
                ('completions', models.IntegerField(default=0)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('avg_rating', models.FloatField(default=0.0)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='masterclasses.masterclass')),
            ],
            options={
                'verbose_name': 'Masterclass Analytics',
                'verbose_name_plural': 'Masterclass Analytics',
                'ordering': ['-date'],
                'unique_together': {('masterclass', 'date')},
            },
        ),
    ]
