# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_certificateanalytics_revenueanalytics_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CertificateAnalytics',
        ),
        migrations.AlterUniqueTogether(
            name='engagementmetrics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='engagementmetrics',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='industrytraininganalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='industrytraininganalytics',
            name='industry',
        ),
        migrations.AlterUniqueTogether(
            name='instructoranalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='instructor',
        ),
        migrations.AlterUniqueTogether(
            name='masterclassanalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='masterclassanalytics',
            name='masterclass',
        ),
        migrations.DeleteModel(
            name='RevenueAnalytics',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='avg_session_duration',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='certificates_issued',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='completion_rate',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='course_completions',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='daily_active_users',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='engagement_score',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='new_enrollments',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='retention_rate',
        ),
        migrations.RemoveField(
            model_name='platformanalytics',
            name='total_revenue',
        ),
        migrations.DeleteModel(
            name='EngagementMetrics',
        ),
        migrations.DeleteModel(
            name='IndustryTrainingAnalytics',
        ),
        migrations.DeleteModel(
            name='InstructorAnalytics',
        ),
        migrations.DeleteModel(
            name='MasterclassAnalytics',
        ),
    ]
