# Generated by Django 4.2.16 on 2026-02-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicertscourse',
            name='active',
            field=models.BooleanField(default=True, help_text='If checked, training is currently running and available for enrollment'),
        ),
    ]
