# Generated by Django 5.2.10 on 2026-01-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='lms_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
