# Generated by Django 4.2.16 on 2026-02-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0002_aicertscourse_active'),
        ('industry_based_training', '0002_alter_aicertscourse_lms_id'),
    ]

    operations = [
    ]
