# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0003_merge_20260216_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicertscourse',
            name='active',
        ),
    ]
