# Generated by Django 4.2.16 on 2026-03-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0004_remove_aicertscourse_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicertscourse',
            name='price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Course price in USD', max_digits=10, null=True),
        ),
    ]
