# Generated by Django 4.2.16 on 2026-03-16 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0005_add_price_usd_to_aicertscourse'),
    ]

    operations = [
    ]
