# Generated by Django 4.2.16 on 2026-03-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_africanbank_africancountry_bankaccounttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('industry_based_training', '0006_auto_20260316_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryTrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('industry_training', 'Industry Training'), ('role_training', 'Role Training')], help_text='Type of industry/role training', max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out'), ('refunded', 'Refunded')], default='pending', help_text='Current enrollment status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partial Payment'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', help_text='Payment status', max_length=20)),
                ('aicerts_user_id', models.PositiveIntegerField(blank=True, help_text='User ID on AICerts LMS', null=True)),
                ('aicerts_enrollment_ids', models.JSONField(blank=True, default=list, help_text='List of AICerts enrollment IDs for each course')),
                ('aicerts_already_enrolled', models.BooleanField(default=False, help_text='Was user already enrolled when we tried to enroll?')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When enrollment was created')),
                ('started_at', models.DateTimeField(blank=True, help_text='When learner started the course', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When learner completed the course', null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time learner accessed the course on AICerts', null=True)),
                ('synced_at', models.DateTimeField(blank=True, help_text='When last synced with AICerts', null=True)),
                ('sync_attempts', models.PositiveIntegerField(default=0, help_text='Number of sync attempts')),
                ('sync_error', models.TextField(blank=True, help_text='Error message from last sync attempt', null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid for this enrollment', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', help_text='Currency of payment', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional enrollment metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('payment_transaction', models.ForeignKey(blank=True, help_text='Associated payment transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_training_enrollments', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(help_text='Enrolled learner', on_delete=django.db.models.deletion.CASCADE, related_name='industry_training_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Industry Training Enrollment',
                'verbose_name_plural': 'Industry Training Enrollments',
                'db_table': 'industry_training_enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='industry_tr_user_id_e3a82d_idx'), models.Index(fields=['user', 'enrollment_type'], name='industry_tr_user_id_7db499_idx'), models.Index(fields=['content_type', 'object_id'], name='industry_tr_content_76f8fb_idx'), models.Index(fields=['status', 'enrolled_at'], name='industry_tr_status_0a0542_idx'), models.Index(fields=['payment_transaction'], name='industry_tr_payment_af543a_idx')],
            },
        ),
    ]
