# Generated by Django 4.2.16 on 2026-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0007_industrytrainingenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicertscourse',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='duration_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='is_offered',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='offering_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='offering_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='our_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom price override', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
