# Generated by Django 4.2.16 on 2026-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0008_aicertscourse_active_aicertscourse_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='venue',
            field=models.TextField(blank=True),
        ),
    ]
