# Generated by Django 4.2.16 on 2026-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0009_alter_aicertscourse_city_alter_aicertscourse_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='country',
            field=models.TextField(blank=True),
        ),
    ]
