# Generated by Django 4.2.16 on 2026-04-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry_based_training', '0010_alter_aicertscourse_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aicertscourse',
            name='active',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='city',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='country',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='is_offered',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='offering_end',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='offering_start',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='our_price_usd',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='venue',
        ),
    ]
