# Generated by Django 4.2.16 on 2026-04-16 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_code', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], help_text='Unique code for the tier (e.g., BRONZE, SILVER)', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable name for the tier', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this tier')),
                ('min_sales', models.PositiveIntegerField(default=0, help_text='Minimum number of sales to qualify for this tier')),
                ('max_sales', models.PositiveIntegerField(blank=True, help_text='Maximum number of sales for this tier (null = unlimited)', null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission percentage (e.g., 15.00 for 15%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('color_code', models.CharField(default='#808080', help_text='Hex color code for UI display (e.g., #CD7F32 for bronze)', max_length=7)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which tiers are displayed (ascending)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tier is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Tier',
                'verbose_name_plural': 'Commission Tiers',
                'ordering': ['display_order', 'tier_code'],
            },
        ),
        migrations.CreateModel(
            name='PartnerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Benefit title (e.g., "Generous Commissions")', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the benefit')),
                ('icon_name', models.CharField(choices=[('monetization_on', 'Monetization'), ('trending_up', 'Trending Up'), ('support_agent', 'Support Agent'), ('public', 'Public/Global'), ('school', 'School/Education'), ('verified', 'Verified'), ('rocket_launch', 'Rocket Launch'), ('groups', 'Groups'), ('insights', 'Insights'), ('workspace_premium', 'Premium'), ('emoji_events', 'Events'), ('card_giftcard', 'Gift Card'), ('schedule', 'Schedule'), ('security', 'Security'), ('speed', 'Speed'), ('star', 'Star'), ('thumb_up', 'Thumb Up'), ('work', 'Work'), ('business', 'Business'), ('person_add', 'Person Add')], default='star', help_text='Material icon name for the UI', max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which benefits are displayed (ascending)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this benefit is currently displayed')),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this benefit is highlighted/featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Benefit',
                'verbose_name_plural': 'Partner Benefits',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProgramInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(help_text='Main introduction text about the partner program')),
                ('mission_title', models.CharField(default='Join Our Mission', max_length=200)),
                ('mission_description', models.TextField(help_text='Mission statement/description')),
                ('who_should_apply_intro', models.TextField(blank=True, help_text='Introduction for "Who Should Apply" section')),
                ('cta_title', models.CharField(default='Ready to Start Earning?', max_length=200)),
                ('cta_description', models.TextField(help_text='Call-to-action description')),
                ('contact_email', models.EmailField(default='partners@hosiacademy.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the partner program is currently accepting applications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner Program Info',
                'verbose_name_plural': 'Partner Program Info',
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('business_name', models.CharField(blank=True, help_text='Business/organization name (if applicable)', max_length=200)),
                ('partner_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('AGENCY', 'Agency'), ('CORPORATE', 'Corporate'), ('INSTITUTION', 'Institution')], default='INDIVIDUAL', max_length=20)),
                ('country', models.CharField(help_text='ISO-2 country code', max_length=2)),
                ('social_media_handles', models.JSONField(default=dict, help_text='Social media handles (Instagram, TikTok, LinkedIn, etc.)')),
                ('estimated_reach', models.PositiveIntegerField(blank=True, help_text='Estimated follower/subscriber count', null=True)),
                ('marketing_experience', models.TextField(blank=True, help_text='Previous marketing/partnership experience')),
                ('target_regions', models.JSONField(default=list, help_text='Target regions/countries for marketing')),
                ('why_partner', models.TextField(blank=True, help_text='Why they want to partner with Hosi Academy')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SUSPENDED', 'Suspended')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this application')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_partner_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partner Application',
                'verbose_name_plural': 'Partner Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
