# Generated by Django 4.2.16 on 2026-01-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('video_url', models.URLField(help_text='HLS manifest URL or MP4 URL')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('subtitle_en_url', models.URLField(blank=True, null=True)),
                ('subtitle_es_url', models.URLField(blank=True, null=True)),
                ('subtitle_fr_url', models.URLField(blank=True, null=True)),
                ('is_preview', models.BooleanField(default=False, help_text='Can be viewed without enrollment')),
                ('allow_download', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lessons', to='courses.course')),
            ],
            options={
                'verbose_name': 'Video Lesson',
                'verbose_name_plural': 'Video Lessons',
                'db_table': 'video_lessons',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('last_watched_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='video_content.videolesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Video Progress',
                'verbose_name_plural': 'Video Progress',
                'db_table': 'video_progress',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
