# Generated by Django 5.2.10 on 2026-01-16 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_app', models.CharField(blank=True, choices=[('aicerts_courses', 'AI Certs Course'), ('learnerships', 'Learnership')], help_text='Which app contains this course (aicerts_courses or learnerships)', max_length=50, null=True, verbose_name='Course App')),
                ('course_model', models.CharField(blank=True, help_text="Model name (e.g., 'Course', 'Learnership')", max_length=50, null=True, verbose_name='Course Model')),
                ('course_id', models.BigIntegerField(blank=True, help_text='ID of the course object', null=True, verbose_name='Course ID')),
                ('course_title', models.CharField(blank=True, help_text='Human-friendly title of the course, if available', max_length=255, null=True, verbose_name='Course Title')),
                ('message', models.TextField(help_text='Supports plain text. Future: rich text, voice notes, attachments', verbose_name='Message Content')),
                ('type', models.BooleanField(default=True, help_text='True = Direct user-to-user, False = System announcement/broadcast', verbose_name='Message Type')),
                ('seen', models.BooleanField(default=False, help_text='Has the receiver read this message?', verbose_name='Seen/Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sent At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'communication_message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender'], name='communicati_sender__0e7b4b_idx'), models.Index(fields=['receiver'], name='communicati_receive_88c263_idx'), models.Index(fields=['course_app', 'course_model', 'course_id'], name='communicati_course__e8c045_idx'), models.Index(fields=['created_at'], name='communicati_created_544711_idx'), models.Index(fields=['seen'], name='communicati_seen_457cbb_idx')],
            },
        ),
    ]
