# Generated by Django 5.2.10 on 2026-01-16 22:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageReadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Read At')),
            ],
            options={
                'verbose_name': 'Message Read Receipt',
                'verbose_name_plural': 'Message Read Receipts',
                'db_table': 'communication_messagereadreceipt',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('message', 'New Message'), ('announcement', 'Announcement'), ('course_update', 'Course Update'), ('assignment', 'Assignment'), ('grade', 'Grade'), ('system', 'System')], default='system', max_length=20, verbose_name='Notification Type')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'communication_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPresence',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('away', 'Away'), ('busy', 'Busy'), ('invisible', 'Invisible')], default='offline', max_length=20, verbose_name='Status')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Seen')),
                ('socket_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Socket ID')),
                ('device_info', models.JSONField(blank=True, default=dict, verbose_name='Device Info')),
                ('custom_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Custom Status')),
            ],
            options={
                'verbose_name': 'User Presence',
                'verbose_name_plural': 'User Presences',
                'db_table': 'communication_userpresence',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='JSON array of attachment URLs/metadata', verbose_name='Attachments'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Is this message deleted?', verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Has this message been edited?', verbose_name='Edited'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File'), ('audio', 'Audio'), ('video', 'Video'), ('announcement', 'Announcement'), ('system', 'System'), ('poll', 'Poll')], default='text', help_text='Type of message for Socket.io chat', max_length=20, verbose_name='Message Type'),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional message metadata', verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, help_text='Message this is replying to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='communication.message', verbose_name='Reply To'),
        ),
        migrations.AddField(
            model_name='message',
            name='socket_message_id',
            field=models.CharField(blank=True, help_text='Unique ID from Socket.io for real-time syncing', max_length=100, null=True, unique=True, verbose_name='Socket Message ID'),
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Room Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('chat_type', models.CharField(choices=[('one_on_one', 'Direct Message'), ('group', 'Group Chat'), ('course', 'Course Discussion'), ('community', 'Community'), ('announcement', 'Announcements'), ('support', 'Support')], default='group', max_length=20, verbose_name='Chat Type')),
                ('course_app', models.CharField(blank=True, choices=[('aicerts_courses', 'AI Certs Course'), ('learnerships', 'Learnership')], max_length=50, null=True, verbose_name='Course App')),
                ('course_model', models.CharField(blank=True, max_length=50, null=True, verbose_name='Course Model')),
                ('course_id', models.BigIntegerField(blank=True, null=True, verbose_name='Course ID')),
                ('course_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Title')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archived')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Muted')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Settings')),
                ('last_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_in_room', to='communication.message', verbose_name='Last Message')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
                'db_table': 'communication_chatroom',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('moderator', 'Moderator'), ('member', 'Member'), ('instructor', 'Instructor'), ('facilitator', 'Facilitator'), ('learner', 'Learner')], default='member', max_length=20, verbose_name='Role')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Joined At')),
                ('last_read_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Last Read At')),
                ('is_muted', models.BooleanField(default=False, verbose_name='Muted')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications Enabled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='communication.chatroom', verbose_name='Chat Room')),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
                'db_table': 'communication_chatparticipant',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(blank=True, help_text='Socket.io chat room reference', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='communication.chatroom', verbose_name='Chat Room'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat_room', 'created_at'], name='communicati_chat_ro_780abe_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['socket_message_id'], name='communicati_socket__90ba24_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='communicati_message_88f192_idx'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communication.message', verbose_name='Message'),
        ),
        migrations.AddField(
            model_name='messagereadreceipt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communication.message', verbose_name='Related Message'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['course_app', 'course_model', 'course_id'], name='communicati_course__2697a7_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['chat_type'], name='communicati_chat_ty_2502be_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['created_at'], name='communicati_created_d63757_idx'),
        ),
        migrations.AddIndex(
            model_name='chatparticipant',
            index=models.Index(fields=['user', 'chat_room'], name='communicati_user_id_e1dcf5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatparticipant',
            unique_together={('chat_room', 'user')},
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['message', 'user'], name='communicati_message_b1067e_idx'),
        ),
        migrations.AddIndex(
            model_name='messagereadreceipt',
            index=models.Index(fields=['read_at'], name='communicati_read_at_bb1f44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messagereadreceipt',
            unique_together={('message', 'user')},
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='communicati_user_id_31f58c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='communicati_created_ec53f0_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='communicati_notific_6be787_idx'),
        ),
    ]
