# Generated by Django 4.2.16 on 2026-01-17 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_chat_system'),
        ('communication', '0002_messagereadreceipt_notification_userpresence_and_more'),
    ]

    operations = [
    ]
