# Generated by Django 5.2.10 on 2026-03-09 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb_integration', '0004_rename_bbb_session_session_3c9f0f_idx_session_inv_session_50e17a_idx_and_more'),
        ('communication', '0003_merge_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='bbb_session_info',
            field=models.JSONField(blank=True, default=dict, help_text='Cached BBB session data for quick display', verbose_name='BBB Session Info'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='upcoming_bbb_session',
            field=models.ForeignKey(blank=True, help_text='Next scheduled BBB session for this course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='bbb_integration.livesession', verbose_name='Upcoming BBB Session'),
        ),
        migrations.AddField(
            model_name='message',
            name='bbb_session',
            field=models.ForeignKey(blank=True, help_text='Linked BBB live session for session announcements and reminders', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='bbb_integration.livesession', verbose_name='BBB Session'),
        ),
    ]
