# Generated by Django 5.2.10 on 2026-01-16 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(blank=True, help_text='Category or name for this log entry', max_length=191, null=True, verbose_name='Log Name')),
                ('description', models.TextField(help_text='Detailed description of the activity', verbose_name='Description')),
                ('subject_app', models.CharField(blank=True, help_text='App containing the subject (e.g., aicerts_courses, learnerships, users)', max_length=50, null=True, verbose_name='Subject App')),
                ('subject_model', models.CharField(blank=True, help_text='Model name of the subject', max_length=191, null=True, verbose_name='Subject Model')),
                ('subject_id', models.BigIntegerField(blank=True, help_text='ID of the subject object', null=True, verbose_name='Subject ID')),
                ('causer_app', models.CharField(blank=True, help_text="App containing the causer (usually 'users')", max_length=50, null=True, verbose_name='Causer App')),
                ('causer_model', models.CharField(blank=True, help_text='Model name of the causer', max_length=191, null=True, verbose_name='Causer Model')),
                ('causer_id', models.BigIntegerField(blank=True, help_text='ID of the causer object (usually User ID)', null=True, verbose_name='Causer ID')),
                ('properties', models.JSONField(blank=True, help_text='Additional properties/metadata in JSON format', null=True, verbose_name='Properties')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['log_name'], name='activity_lo_log_nam_eb3d0f_idx'), models.Index(fields=['subject_app', 'subject_model', 'subject_id'], name='activity_lo_subject_334907_idx'), models.Index(fields=['causer_app', 'causer_model', 'causer_id'], name='activity_lo_causer__8efd1b_idx'), models.Index(fields=['created_at'], name='activity_lo_created_8906e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message Content')),
                ('type', models.BooleanField(default=True, help_text='True = user message, False = system message', verbose_name='Message Type')),
                ('seen', models.BooleanField(default=False, verbose_name='Seen Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('reciever', models.ForeignKey(blank=True, help_text='Message receiver', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
                ('sender', models.ForeignKey(blank=True, help_text='Message sender', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Legacy Message',
                'verbose_name_plural': 'Legacy Messages',
                'db_table': 'messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_app', models.CharField(blank=True, choices=[('aicerts_courses', 'AI Certs Course'), ('learnerships', 'Learnership')], help_text='Which app contains this course (aicerts_courses or learnerships)', max_length=50, null=True, verbose_name='Course App')),
                ('course_model', models.CharField(blank=True, help_text="Model name (e.g., 'Course', 'Learnership')", max_length=50, null=True, verbose_name='Course Model')),
                ('course_id', models.BigIntegerField(blank=True, help_text='ID of the course object', null=True, verbose_name='Course ID')),
                ('message_id', models.IntegerField(blank=True, help_text='Related message ID from communication app', null=True, verbose_name='Message ID')),
                ('course_comment', models.IntegerField(blank=True, help_text='ID of a course comment', null=True, verbose_name='Course Comment ID')),
                ('course_review', models.IntegerField(blank=True, help_text='ID of a course review', null=True, verbose_name='Course Review ID')),
                ('course_enrolled', models.IntegerField(blank=True, help_text='ID of a course enrollment', null=True, verbose_name='Course Enrollment ID')),
                ('status', models.BooleanField(default=False, help_text='True = read, False = unread', verbose_name='Read Status')),
                ('notification_type', models.CharField(blank=True, help_text='Type of notification: comment, review, enrollment, message, etc.', max_length=50, null=True, verbose_name='Notification Type')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Notification Title')),
                ('content', models.TextField(blank=True, help_text='Full notification message/content', null=True, verbose_name='Notification Content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('author', models.ForeignKey(blank=True, help_text='User who triggered the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('user', models.ForeignKey(help_text='User receiving the notification', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='notificatio_user_id_8ab96f_idx'), models.Index(fields=['course_app', 'course_model', 'course_id'], name='notificatio_course__151154_idx'), models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx')],
            },
        ),
    ]
