# Generated by Django 5.2.10 on 2026-01-16 08:35

import apps.instructors.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facilitator_id', models.CharField(default=apps.instructors.models.generate_instructor_id, max_length=50, unique=True, verbose_name='Facilitator ID')),
                ('facilitator_type', models.CharField(choices=[('facilitator', 'Facilitator'), ('trainer', 'Trainer'), ('assessor', 'Assessor'), ('moderator', 'Moderator'), ('coach', 'Coach'), ('mentor', 'Mentor')], default='facilitator', max_length=20, verbose_name='Facilitator Type')),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee/Staff Number')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Department')),
                ('specialization', models.TextField(blank=True, help_text='Subject areas or skills this facilitator specializes in', null=True, verbose_name='Area of Specialization')),
                ('qualifications', models.TextField(blank=True, help_text='Educational and professional qualifications', null=True, verbose_name='Qualifications')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('work_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Phone')),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Work Email')),
                ('office_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Office/Location')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if facilitator is currently available for new course assignments', verbose_name='Available for Assignments')),
                ('max_courses', models.PositiveIntegerField(default=5, help_text='Maximum number of courses this facilitator can handle simultaneously', verbose_name='Maximum Concurrent Courses')),
                ('availability_notes', models.TextField(blank=True, help_text='Notes about availability, preferences, or constraints', null=True, verbose_name='Availability Notes')),
                ('overall_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Overall Performance Rating')),
                ('performance_band', models.CharField(blank=True, choices=[('excellent', 'Excellent (90-100%)'), ('good', 'Good (75-89%)'), ('satisfactory', 'Satisfactory (60-74%)'), ('needs_improvement', 'Needs Improvement (40-59%)'), ('poor', 'Poor (<40%)')], max_length=30, null=True, verbose_name='Performance Band')),
                ('total_courses_taught', models.PositiveIntegerField(default=0, verbose_name='Total Courses Taught')),
                ('total_students_taught', models.PositiveIntegerField(default=0, verbose_name='Total Students Taught')),
                ('average_student_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Student Rating')),
                ('completion_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Average Course Completion Rate')),
                ('last_performance_review', models.DateField(blank=True, null=True, verbose_name='Last Performance Review')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='Date Hired/Appointed')),
                ('contract_expiry', models.DateField(blank=True, null=True, verbose_name='Contract Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Facilitator')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Administrative Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
            ],
            options={
                'verbose_name': 'Facilitator Profile',
                'verbose_name_plural': 'Facilitator Profiles',
                'db_table': 'facilitator_profiles',
                'ordering': ['user__name', 'facilitator_id'],
            },
        ),
        migrations.CreateModel(
            name='FacilitatorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('course_creation', 'Course Created'), ('content_upload', 'Content Uploaded'), ('assessment_created', 'Assessment Created'), ('live_session', 'Live Session Conducted'), ('student_feedback', 'Student Feedback Provided'), ('grading', 'Grading Completed'), ('forum_participation', 'Forum Participation'), ('announcement', 'Announcement Posted'), ('resource_shared', 'Resource Shared'), ('meeting_attended', 'Meeting Attended'), ('training_completed', 'Training Completed'), ('other', 'Other Activity')], max_length=50, verbose_name='Activity Type')),
                ('description', models.TextField(verbose_name='Activity Description')),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Activity Date/Time')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Activity')),
                ('verification_notes', models.TextField(blank=True, null=True, verbose_name='Verification Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator_activities', to='courses.course', verbose_name='Course (if applicable)')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
            ],
            options={
                'verbose_name': 'Facilitator Activity Log',
                'verbose_name_plural': 'Facilitator Activity Logs',
                'db_table': 'facilitator_activity_logs',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.CharField(default=apps.instructors.models.generate_assignment_id, max_length=50, unique=True, verbose_name='Assignment ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Assignment Status')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date Assigned')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('expected_end_date', models.DateField(verbose_name='Expected End Date')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Actual End Date')),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes about this specific assignment', null=True, verbose_name='Assignment Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_assignments', to='courses.course', verbose_name='Course')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
            ],
            options={
                'verbose_name': 'Course Assignment',
                'verbose_name_plural': 'Course Assignments',
                'db_table': 'course_assignments',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='FacilitatorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating (0-5)')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Review/Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_ratings', to='courses.course', verbose_name='Course')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Facilitator Rating',
                'verbose_name_plural': 'Facilitator Ratings',
                'db_table': 'facilitator_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appraisal_id', models.CharField(default=apps.instructors.models.generate_appraisal_id, max_length=50, unique=True, verbose_name='Appraisal ID')),
                ('appraisal_type', models.CharField(choices=[('quarterly', 'Quarterly Review'), ('mid_year', 'Mid-Year Review'), ('annual', 'Annual Review'), ('probation', 'Probation Review'), ('promotion', 'Promotion Review'), ('special', 'Special Review')], max_length=20, verbose_name='Appraisal Type')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('appraisal_period_start', models.DateField(verbose_name='Appraisal Period Start')),
                ('appraisal_period_end', models.DateField(verbose_name='Appraisal Period End')),
                ('scheduled_date', models.DateField(verbose_name='Scheduled Date')),
                ('overall_score', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Overall Score')),
                ('knowledge_expertise', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Knowledge & Expertise')),
                ('teaching_effectiveness', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Teaching Effectiveness')),
                ('student_engagement', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Student Engagement')),
                ('communication_skills', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Communication Skills')),
                ('professionalism', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)], verbose_name='Professionalism')),
                ('strengths', models.TextField(help_text='Key strengths demonstrated during the appraisal period', verbose_name='Strengths')),
                ('areas_for_improvement', models.TextField(help_text='Areas where improvement is needed', verbose_name='Areas for Improvement')),
                ('development_plan', models.TextField(blank=True, help_text='Specific development plan for the next period', null=True, verbose_name='Development Plan')),
                ('review_date', models.DateField(blank=True, null=True, verbose_name='Review Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator_appraisals_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By')),
            ],
            options={
                'verbose_name': 'Performance Appraisal',
                'verbose_name_plural': 'Performance Appraisals',
                'db_table': 'performance_appraisals',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='FacilitatorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Period Start')),
                ('period_end', models.DateField(verbose_name='Period End')),
                ('courses_completed', models.PositiveIntegerField(default=0, verbose_name='Courses Completed')),
                ('courses_ongoing', models.PositiveIntegerField(default=0, verbose_name='Courses Ongoing')),
                ('total_students', models.PositiveIntegerField(default=0, verbose_name='Total Students')),
                ('average_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Rating')),
                ('completion_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Completion Rate')),
                ('student_retention', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Student Retention Rate')),
                ('activity_hours', models.FloatField(default=0.0, verbose_name='Total Activity Hours')),
                ('content_created', models.PositiveIntegerField(default=0, verbose_name='Content Items Created')),
                ('assessments_created', models.PositiveIntegerField(default=0, verbose_name='Assessments Created')),
                ('is_current', models.BooleanField(default=False, verbose_name='Current Period Analytics')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
            ],
            options={
                'verbose_name': 'Facilitator Analytics',
                'verbose_name_plural': 'Facilitator Analytics',
                'db_table': 'facilitator_analytics',
                'ordering': ['-period_end'],
                'unique_together': {('facilitator', 'period_start', 'period_end')},
            },
        ),
    ]
