# Generated by Django 5.2.10 on 2026-01-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('instructors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_assignments', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='facilitatoractivitylog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator_activities', to='courses.course', verbose_name='Course (if applicable)'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='facilitatoranalytics',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='instructors.facilitatorprofile', verbose_name='Facilitator'),
        ),
        migrations.AddField(
            model_name='facilitatoractivitylog',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='instructors.facilitatorprofile', verbose_name='Facilitator'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='instructors.facilitatorprofile', verbose_name='Facilitator'),
        ),
        migrations.AddField(
            model_name='facilitatorrating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_ratings', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='facilitatorrating',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='instructors.facilitatorprofile', verbose_name='Facilitator'),
        ),
        migrations.AddField(
            model_name='facilitatorrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='performanceappraisal',
            name='facilitator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='instructors.facilitatorprofile', verbose_name='Facilitator'),
        ),
        migrations.AddField(
            model_name='performanceappraisal',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilitator_appraisals_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.AlterUniqueTogether(
            name='facilitatoranalytics',
            unique_together={('facilitator', 'period_start', 'period_end')},
        ),
    ]
