# Generated by Django 4.2.16 on 2026-02-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitatorprofile',
            name='certificates',
            field=models.FileField(blank=True, null=True, upload_to='instructors/certificates/', verbose_name='Certificates/Documents'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='instructors/cvs/', verbose_name='Curriculum Vitae'),
        ),
    ]
