# Generated by Django 4.2.16 on 2026-02-12 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        ('instructors', '0003_facilitatorprofile_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(models.Q(('app_label', 'learnerships'), ('model', 'learnershipprogramme')), models.Q(('app_label', 'masterclasses'), ('model', 'masterclass')), models.Q(('app_label', 'courses'), ('model', 'course')), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='is_aicerts_instructor',
            field=models.BooleanField(default=False, verbose_name='Instructs AI Certs'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='is_corporate_instructor',
            field=models.BooleanField(default=False, verbose_name='Instructs Corporate Training'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='is_learnership_instructor',
            field=models.BooleanField(default=False, verbose_name='Instructs Learnerships'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='is_masterclass_instructor',
            field=models.BooleanField(default=False, verbose_name='Instructs Masterclasses'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='primary_provider',
            field=models.ForeignKey(blank=True, help_text='The main training provider this facilitator is aligned with', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aligned_instructors', to='courses.courseprovider', verbose_name='Primary Course Provider'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_assignments', to='courses.course', verbose_name='Course'),
        ),
    ]
