# Generated by Django 4.2.16 on 2026-02-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_courseassignment_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='accrued_hours',
            field=models.FloatField(default=0.0, verbose_name='Accrued Hours'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='is_accrued',
            field=models.BooleanField(default=False, verbose_name='Accrual Processed'),
        ),
        migrations.AddField(
            model_name='facilitatorprofile',
            name='is_suspended',
            field=models.BooleanField(default=False, verbose_name='Suspended'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='status',
            field=models.CharField(default='pending', verbose_name='Assignment Status'),
        ),
    ]
