# Generated by Django 4.2.16 on 2026-02-12 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0005_courseassignment_accrued_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('hours', models.FloatField(verbose_name='Overtime Hours')),
                ('reason', models.TextField(verbose_name='Reason for Overtime')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_logs', to='instructors.courseassignment', verbose_name='Assignment')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_requests', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
            ],
            options={
                'verbose_name': 'Overtime Request',
                'verbose_name_plural': 'Overtime Requests',
                'db_table': 'facilitator_overtime_requests',
            },
        ),
        migrations.CreateModel(
            name='EarningsAccrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('accrued', 'Accrued'), ('paid', 'Paid Out'), ('cancelled', 'Cancelled')], default='accrued', max_length=20)),
                ('accrued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accruals', to='instructors.courseassignment')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='instructors.facilitatorprofile', verbose_name='Facilitator')),
                ('overtime_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accrual', to='instructors.overtimerequest')),
            ],
            options={
                'verbose_name': 'Earnings Accrual',
                'verbose_name_plural': 'Earnings Accruals',
                'db_table': 'facilitator_earnings_accruals',
            },
        ),
    ]
