# Generated by Django 4.2.16 on 2026-02-12 14:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0006_overtimerequest_earningsaccrual'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitatorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('onsite', 'On-site Training'), ('online', 'BigBlueButton Session')], default='onsite', max_length=20)),
                ('clock_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('actual_duration', models.FloatField(default=0.0, help_text='Total hours clocked')),
                ('accrued_hours', models.FloatField(default=0.0, help_text='Hours allowed by system based on schedule')),
                ('overtime_hours', models.FloatField(default=0.0, help_text='Hours above 8h limit')),
                ('justification', models.TextField(blank=True, help_text='Required if duration > 8 hours', null=True)),
                ('status', models.CharField(choices=[('active', 'Clocked In'), ('completed', 'Completed'), ('processed', 'Accrued to Balance')], default='active', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='instructors.courseassignment')),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='instructors.facilitatorprofile')),
            ],
            options={
                'verbose_name': 'Facilitator Attendance',
                'verbose_name_plural': 'Facilitator Attendance',
                'db_table': 'facilitator_attendance',
            },
        ),
        migrations.CreateModel(
            name='AssignmentDailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('scheduled_hours', models.FloatField(default=8.0)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_schedules', to='instructors.courseassignment')),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'db_table': 'facilitator_assignment_schedules',
                'unique_together': {('assignment', 'date')},
            },
        ),
    ]
