# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('instructors', '0007_facilitatorattendance_assignmentdailyschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='earningsaccrual',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='earningsaccrual',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='earningsaccrual',
            name='overtime_request',
        ),
        migrations.RemoveField(
            model_name='facilitatorattendance',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='facilitatorattendance',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='overtimerequest',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='accrued_hours',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='is_accrued',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='is_aicerts_instructor',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='is_corporate_instructor',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='is_learnership_instructor',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='is_masterclass_instructor',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='is_suspended',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='primary_provider',
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_assignments', to='courses.course', verbose_name='Course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Assignment Status'),
        ),
        migrations.DeleteModel(
            name='AssignmentDailySchedule',
        ),
        migrations.DeleteModel(
            name='EarningsAccrual',
        ),
        migrations.DeleteModel(
            name='FacilitatorAttendance',
        ),
        migrations.DeleteModel(
            name='OvertimeRequest',
        ),
    ]
