# Generated by Django 4.2.16 on 2026-03-16 07:47

import apps.instructors.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_africanbank_africancountry_bankaccounttemplate_and_more'),
        ('organizations', '0003_company_companylearner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localization', '0009_alter_city_options_state_alter_city_unique_together_and_more'),
        ('courses', '0001_initial'),
        ('instructors', '0009_instructorapplication_instructorstatuslog_instructoranalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_id', models.CharField(default=apps.instructors.models.generate_instructor_id, max_length=50, unique=True, verbose_name='Instructor ID')),
                ('instructor_type', models.CharField(choices=[('facilitator', 'Facilitator'), ('trainer', 'Trainer'), ('assessor', 'Assessor'), ('moderator', 'Moderator'), ('coach', 'Coach'), ('mentor', 'Mentor')], default='facilitator', max_length=20, verbose_name='Instructor Type')),
                ('employee_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Employee/Staff Number')),
                ('department', models.CharField(blank=True, max_length=200, null=True, verbose_name='Department')),
                ('specialization', models.TextField(blank=True, help_text='Subject areas or skills this instructor specializes in', null=True, verbose_name='Area of Specialization')),
                ('qualifications', models.TextField(blank=True, help_text='Educational and professional qualifications', null=True, verbose_name='Qualifications')),
                ('years_experience', models.PositiveIntegerField(default=0, verbose_name='Years of Experience')),
                ('work_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Phone')),
                ('work_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Work Email')),
                ('office_location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Office/Location')),
                ('is_available', models.BooleanField(default=True, help_text='Indicates if instructor is currently available for new course assignments', verbose_name='Available for Assignments')),
                ('max_courses', models.PositiveIntegerField(default=5, help_text='Maximum number of courses this instructor can handle simultaneously', verbose_name='Maximum Concurrent Courses')),
                ('availability_notes', models.TextField(blank=True, help_text='Notes about availability, preferences, or constraints', null=True, verbose_name='Availability Notes')),
                ('overall_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Overall Performance Rating')),
                ('performance_band', models.CharField(blank=True, choices=[('excellent', 'Excellent (90-100%)'), ('good', 'Good (75-89%)'), ('satisfactory', 'Satisfactory (60-74%)'), ('needs_improvement', 'Needs Improvement (40-59%)'), ('poor', 'Poor (<40%)')], max_length=30, null=True, verbose_name='Performance Band')),
                ('total_courses_taught', models.PositiveIntegerField(default=0, verbose_name='Total Courses Taught')),
                ('total_students_taught', models.PositiveIntegerField(default=0, verbose_name='Total Students Taught')),
                ('average_student_rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Student Rating')),
                ('completion_rate', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Average Course Completion Rate')),
                ('last_performance_review', models.DateField(blank=True, null=True, verbose_name='Last Performance Review')),
                ('date_hired', models.DateField(blank=True, null=True, verbose_name='Date Hired/Appointed')),
                ('contract_expiry', models.DateField(blank=True, null=True, verbose_name='Contract Expiry Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active Instructor')),
                ('assignment_date', models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when instructor was assigned to HR Admin', null=True, verbose_name='Assignment Date')),
                ('assignment_type', models.CharField(choices=[('country_based', 'Country-Based'), ('specialization', 'Specialization-Based'), ('performance', 'Performance-Based'), ('manual', 'Manual Assignment'), ('auto', 'Auto-Assigned')], default='country_based', help_text='How this instructor was assigned to HR Admin', max_length=50, verbose_name='Assignment Type')),
                ('assignment_notes', models.TextField(blank=True, help_text='Notes about the instructor assignment', null=True, verbose_name='Assignment Notes')),
                ('instructor_user_id', models.BigIntegerField(blank=True, help_text='Legacy user ID field - use user field instead', null=True, verbose_name='Instructor User ID (Legacy)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Administrative Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'db_table': 'instructors',
                'ordering': ['user__name', 'instructor_id'],
            },
        ),
        migrations.CreateModel(
            name='InstructorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('course_creation', 'Course Created'), ('content_upload', 'Content Uploaded'), ('assessment_created', 'Assessment Created'), ('live_session', 'Live Session Conducted'), ('student_feedback', 'Student Feedback Provided'), ('grading', 'Grading Completed'), ('forum_participation', 'Forum Participation'), ('announcement', 'Announcement Posted'), ('resource_shared', 'Resource Shared'), ('meeting_attended', 'Meeting Attended'), ('training_completed', 'Training Completed'), ('other', 'Other Activity')], max_length=50, verbose_name='Activity Type')),
                ('description', models.TextField(verbose_name='Activity Description')),
                ('activity_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Activity Date/Time')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified Activity')),
                ('verification_notes', models.TextField(blank=True, null=True, verbose_name='Verification Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor Activity Log',
                'verbose_name_plural': 'Instructor Activity Logs',
                'db_table': 'instructor_activity_logs',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='InstructorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Rating (0-5)')),
                ('review', models.TextField(blank=True, null=True, verbose_name='Review/Comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instructor Rating',
                'verbose_name_plural': 'Instructor Ratings',
                'db_table': 'instructor_ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='facilitatoractivitylog',
            name='course',
        ),
        migrations.RemoveField(
            model_name='facilitatoractivitylog',
            name='facilitator',
        ),
        migrations.AlterUniqueTogether(
            name='facilitatoranalytics',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='facilitatoranalytics',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='facilitatorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='facilitatorrating',
            name='course',
        ),
        migrations.RemoveField(
            model_name='facilitatorrating',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='facilitatorrating',
            name='student',
        ),
        migrations.RemoveIndex(
            model_name='instructoranalytics',
            name='instructor__country_0aef9b_idx',
        ),
        migrations.RemoveIndex(
            model_name='instructoranalytics',
            name='instructor__instruc_ca7f72_idx',
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='facilitator',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='country',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='course_completion_rate',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='status',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='student_retention_rate',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='total_courses_taught',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='total_live_sessions',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='total_session_attendance',
        ),
        migrations.RemoveField(
            model_name='instructoranalytics',
            name='total_students_taught',
        ),
        migrations.RemoveField(
            model_name='performanceappraisal',
            name='facilitator',
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='activity_hours',
            field=models.FloatField(default=0.0, verbose_name='Total Activity Hours'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='assessments_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Assessments Created'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='completion_rate',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Completion Rate'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='content_created',
            field=models.PositiveIntegerField(default=0, verbose_name='Content Items Created'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='courses_completed',
            field=models.PositiveIntegerField(default=0, verbose_name='Courses Completed'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='courses_ongoing',
            field=models.PositiveIntegerField(default=0, verbose_name='Courses Ongoing'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='is_current',
            field=models.BooleanField(default=False, verbose_name='Current Period Analytics'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='student_retention',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='Student Retention Rate'),
        ),
        migrations.AddField(
            model_name='instructoranalytics',
            name='total_students',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Students'),
        ),
        migrations.AlterField(
            model_name='courseassignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_assignments', to='courses.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='instructoranalytics',
            name='average_rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Average Rating'),
        ),
        migrations.AlterField(
            model_name='instructoranalytics',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instructoranalytics',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instructoranalytics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='performanceappraisal',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_appraisals_conducted', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed By'),
        ),
        migrations.DeleteModel(
            name='FacilitatorActivityLog',
        ),
        migrations.DeleteModel(
            name='FacilitatorAnalytics',
        ),
        migrations.DeleteModel(
            name='FacilitatorProfile',
        ),
        migrations.DeleteModel(
            name='FacilitatorRating',
        ),
        migrations.AddField(
            model_name='instructorrating',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings', to='courses.course', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='instructorrating',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='instructors.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='instructorrating',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_ratings_given', to=settings.AUTH_USER_MODEL, verbose_name='Student'),
        ),
        migrations.AddField(
            model_name='instructoractivitylog',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_activities', to='courses.course', verbose_name='Course (if applicable)'),
        ),
        migrations.AddField(
            model_name='instructoractivitylog',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='instructors.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='assignment_country',
            field=models.ForeignKey(blank=True, help_text='Primary country this instructor is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_instructors', to='localization.country', verbose_name='Assignment Country'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='hr_admin',
            field=models.ForeignKey(blank=True, help_text='HR Administrator responsible for this instructor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_instructors', to='payments.adminrole', verbose_name='HR Admin'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Company/provider this instructor works for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='organizations.company', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilitator_profile', to=settings.AUTH_USER_MODEL, verbose_name='User Account'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='instructors.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='performanceappraisal',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisals', to='instructors.instructor', verbose_name='Instructor'),
        ),
        migrations.AlterField(
            model_name='instructoranalytics',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='instructors.instructor', verbose_name='Instructor'),
        ),
    ]
