# Generated by Django 4.2.16 on 2026-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0011_instructorhoursclaim_instructorovertime_instructorpayrollsummary'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='instructorhoursclaim',
            new_name='instructor__instruc_1b6cdc_idx',
            old_name='instructor__instructo_b6c0d7_idx',
        ),
        migrations.RenameIndex(
            model_name='instructorhoursclaim',
            new_name='instructor__status_2bbc9e_idx',
            old_name='instructor__status_9a0c3b_idx',
        ),
        migrations.RenameIndex(
            model_name='instructorhoursclaim',
            new_name='instructor__year_73616e_idx',
            old_name='instructor__year_mo_8f3d2e_idx',
        ),
        migrations.RenameIndex(
            model_name='instructorovertime',
            new_name='instructor__instruc_f7f731_idx',
            old_name='instructor__instructo_c4e5f2_idx',
        ),
        migrations.RenameIndex(
            model_name='instructorovertime',
            new_name='instructor__overtim_feabc9_idx',
            old_name='instructor__overtime_a8b3c1_idx',
        ),
        migrations.AlterField(
            model_name='instructorhoursclaim',
            name='overtime_justification',
            field=models.TextField(blank=True, help_text='Reason for overtime hours claimed', null=True, verbose_name='Overtime Justification'),
        ),
        migrations.AlterField(
            model_name='instructorhoursclaim',
            name='overtime_rate_multiplier',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Overtime pay multiplier (default 1.5x)', max_digits=3, verbose_name='Overtime Rate Multiplier'),
        ),
        migrations.AlterField(
            model_name='instructorhoursclaim',
            name='session_breakdown',
            field=models.JSONField(default=list, help_text='Detailed breakdown of sessions with dates and durations', verbose_name='Session Breakdown'),
        ),
        migrations.AlterField(
            model_name='instructorhoursclaim',
            name='session_ids',
            field=models.JSONField(default=list, help_text='List of BBB session IDs included in this claim', verbose_name='Session IDs'),
        ),
    ]
