# Generated by Django 4.2.16 on 2026-04-26 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0012_add_smatpay_fee_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instructors', '0012_rename_instructor__instructo_b6c0d7_idx_instructor__instruc_1b6cdc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorCountryAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this country access is currently active', verbose_name='Active')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Granted At')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_accesses', to='localization.country', verbose_name='Country')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_instructor_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Granted By')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_accesses', to='instructors.instructor', verbose_name='Instructor')),
            ],
            options={
                'verbose_name': 'Instructor Country Access',
                'verbose_name_plural': 'Instructor Country Accesses',
                'db_table': 'instructor_country_access',
                'ordering': ['country__name', 'instructor'],
                'indexes': [models.Index(fields=['instructor', 'is_active'], name='instructor__instruc_ec7d88_idx'), models.Index(fields=['country', 'is_active'], name='instructor__country_c82419_idx')],
                'unique_together': {('instructor', 'country')},
            },
        ),
    ]
