# Generated by Django 4.2.16 on 2026-04-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0013_instructorcountryaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_custom_courses',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Custom Selection Courses'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_industry_courses',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Industry Specific & Role Based Courses'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_learnerships',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Learnerships'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_masterclasses',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Masterclasses'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='main_streams',
            field=models.JSONField(blank=True, default=list, help_text="e.g., ['Cybersecurity', 'AI & Blockchain']", verbose_name='Main Streams'),
        ),
    ]
