# Generated by Django 4.2.16 on 2026-04-26 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_instructorapplication_interested_custom_courses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorapplication',
            name='interested_custom_courses',
        ),
        migrations.RemoveField(
            model_name='instructorapplication',
            name='interested_industry_courses',
        ),
        migrations.RemoveField(
            model_name='instructorapplication',
            name='interested_learnerships',
        ),
        migrations.RemoveField(
            model_name='instructorapplication',
            name='interested_masterclasses',
        ),
        migrations.RemoveField(
            model_name='instructorapplication',
            name='main_streams',
        ),
        migrations.DeleteModel(
            name='InstructorCountryAccess',
        ),
    ]
