# Generated by Django 4.2.16 on 2026-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_remove_instructorapplication_interested_custom_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_custom_courses',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Custom Courses'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_industry_courses',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Industry/Role Based Courses'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_learnerships',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Learnerships'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='interested_masterclasses',
            field=models.JSONField(blank=True, default=list, verbose_name='Interested Masterclasses'),
        ),
        migrations.AddField(
            model_name='instructorapplication',
            name='main_streams',
            field=models.JSONField(blank=True, default=list, verbose_name='Main Streams (Cybersecurity/AI & Blockchain)'),
        ),
    ]
