# Generated by Django 4.2.16 on 2026-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aicerts_instructor_courses',
            field=models.ManyToManyField(blank=True, help_text='Courses this instructor is designated to teach on AICERTs', related_name='designated_instructors', to='aicerts_courses.aicertscourse'),
        ),
        migrations.AddField(
            model_name='user',
            name='aicerts_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time user data was synced with AICERTs', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='aicerts_user_id',
            field=models.PositiveIntegerField(blank=True, help_text='User ID on AICERTs LMS (learn.aicerts.io)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token_created_at',
            field=models.DateTimeField(blank=True, help_text='When verification token was generated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_aicerts_instructor',
            field=models.BooleanField(default=False, help_text='Is this user a registered AICERTs instructor?'),
        ),
    ]
