# Generated by Django 4.2.16 on 2026-01-25 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0003_alter_learnershipprogramme_title'),
        ('users', '0002_user_aicerts_instructor_courses_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfileField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label', models.CharField(max_length=255)),
                ('field_name', models.CharField(help_text="Slug-style name (e.g., 'id_number')", max_length=100)),
                ('field_type', models.CharField(default='text', help_text='text, number, date, select', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='learnerships.courseprovider')),
            ],
            options={
                'verbose_name': 'Custom Profile Field',
                'verbose_name_plural': 'Custom Profile Fields',
                'db_table': 'custom_profile_fields',
                'ordering': ['display_order', 'field_label'],
            },
        ),
        migrations.CreateModel(
            name='CourseProviderEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', help_text='Enrollment status (pending, active, completed, cancelled)', max_length=50)),
                ('programme_type', models.CharField(blank=True, help_text="e.g., 'learnership', 'masterclass', 'short_course'", max_length=100, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_enrollments', to='learnerships.course')),
                ('learnership_programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programme_enrollments', to='learnerships.learnershipprogramme')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_enrollments', to='learnerships.courseprovider')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_provider_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course Provider Enrollment',
                'verbose_name_plural': 'Course Provider Enrollments',
                'db_table': 'course_provider_enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCustomProfileValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_values', to='users.customprofilefield')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_profile_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Custom Profile Value',
                'verbose_name_plural': 'User Custom Profile Values',
                'db_table': 'user_custom_profile_values',
                'unique_together': {('user', 'field')},
            },
        ),
    ]
