# Generated by Django 4.2.16 on 2026-01-29 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customprofilefield_courseproviderenrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender for default profile picture selection', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intro_video',
            field=models.FileField(blank=True, help_text='30-second intro video', null=True, upload_to='profiles/videos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude for proximity calculation', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude for proximity calculation', max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Profile gallery image', upload_to='profiles/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=255)),
                ('display_order', models.IntegerField(default=0, help_text='Order in gallery (lower numbers show first)')),
                ('is_primary', models.BooleanField(default=False, help_text='Set as primary profile picture')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Image',
                'verbose_name_plural': 'Profile Images',
                'db_table': 'user_profile_images',
                'ordering': ['display_order', '-uploaded_at'],
                'indexes': [models.Index(fields=['user', 'is_primary'], name='user_profil_user_id_221551_idx')],
            },
        ),
    ]
