# Generated by Django 4.2.16 on 2026-01-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0005_state_city'),
        ('users', '0004_user_gender_user_intro_video_user_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='based_city',
            field=models.ForeignKey(blank=True, help_text='City where user is currently based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_based_here', to='localization.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='based_country',
            field=models.ForeignKey(blank=True, help_text='Country where user is currently based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_based_here', to='localization.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='based_state',
            field=models.ForeignKey(blank=True, help_text='State/Region where user is currently based', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_based_here', to='localization.state'),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_city',
            field=models.ForeignKey(blank=True, help_text='City of origin/birth', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_from_here', to='localization.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_country',
            field=models.ForeignKey(blank=True, help_text='Country of origin/birth', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_from_here', to='localization.country'),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_state',
            field=models.ForeignKey(blank=True, help_text='State/Region of origin/birth', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_from_here', to='localization.state'),
        ),
    ]
