# Generated by Django 4.2.16 on 2026-02-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_dating_app_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hourly Rate'),
        ),
    ]
