# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_hourly_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customprofilefield',
            name='provider',
        ),
        migrations.AlterUniqueTogether(
            name='usercustomprofilevalue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercustomprofilevalue',
            name='field',
        ),
        migrations.RemoveField(
            model_name='usercustomprofilevalue',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aicerts_instructor_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aicerts_synced_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='aicerts_user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_verification_token_created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hourly_rate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_aicerts_instructor',
        ),
        migrations.DeleteModel(
            name='CourseProviderEnrollment',
        ),
        migrations.DeleteModel(
            name='CustomProfileField',
        ),
        migrations.DeleteModel(
            name='UserCustomProfileValue',
        ),
    ]
