# Generated by Django 4.2.16 on 2026-02-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0009_alter_city_options_state_alter_city_unique_together_and_more'),
        ('users', '0008_remove_customprofilefield_provider_and_more'),
    ]

    operations = [
        migrations.RunSQL("UPDATE users SET city = NULL, country = NULL;"),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='localization.state', verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='localization.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='localization.country', verbose_name='Country'),
        ),
    ]
