# Generated by Django 4.2.16 on 2026-02-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0001_initial'),
        ('aicerts_integration', '0001_initial'),
        ('users', '0009_user_state_alter_user_city_alter_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_aicerts_instructor',
            field=models.BooleanField(default=False, verbose_name='Is AiCerts Instructor'),
        ),
        migrations.AddField(
            model_name='user',
            name='aicerts_user_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='AiCerts User ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='aicerts_synced_at',
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                max_digits=20,
                null=True,
                verbose_name='AiCerts Sync Timestamp',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='aicerts_instructor_courses',
            field=models.ManyToManyField(
                blank=True,
                related_name='instructors',
                through='aicerts_integration.AICertsInstructorDesignation',
                to='aicerts_courses.aicertscourse',
            ),
        ),
    ]
