# Generated by Django 4.2.16 on 2026-02-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_aicerts_instructor_courses_and_more'),
    ]

    operations = [
    ]
