# Generated by Django 4.2.16 on 2026-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_user_role_profile_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verify',
            field=models.CharField(default='0', max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
