# Generated by Django 4.2.16 on 2026-04-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_address_alter_user_email_verify_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_executive',
            field=models.BooleanField(default=False, help_text='Can send platform-wide announcements and bulk emails', verbose_name='Is Executive Administrator'),
        ),
    ]
