# Generated by Django 4.2.16 on 2026-04-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_user_is_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tiktok',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='TikTok Handle'),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=191, null=True, verbose_name='X (Twitter) Handle'),
        ),
    ]
