# Generated by Django 4.2.16 on 2026-04-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_tiktok_alter_user_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_login_enabled',
            field=models.BooleanField(default=True, help_text='Allow login via password. If False, only OTP login is permitted.'),
        ),
    ]
