# Generated by Django 4.2.16 on 2026-04-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_user_is_password_login_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending Email Change'), ('completed', 'Onboarding Completed')], default='completed', help_text='Used to force new admins to change their dummy emails on first login.', max_length=20, verbose_name='Onboarding Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_password_login_enabled',
            field=models.BooleanField(default=True, help_text='If disabled, user MUST use OTP for login. More secure.', verbose_name='Password Login Enabled'),
        ),
    ]
