# Generated by Django 4.2.16 on 2026-04-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_authotp_remove_user_admin_profile_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='admin_profile_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='instructor_profile_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_executive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_login_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='student_profile_link',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tiktok',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verify',
            field=models.CharField(default='0', max_length=191),
        ),
        migrations.AlterField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
