# Generated by Django 4.2.16 on 2026-02-03 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0005_paymenttransaction_company_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learnerships', '0005_learnershipprogramme_accreditation_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionalEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry', 'Industry Training'), ('custom_selection', 'Custom Selection')], max_length=20, verbose_name='Enrollment Type')),
                ('status', models.CharField(choices=[('cash_pending', 'Cash Payment Pending'), ('provisional', 'Provisional (Awaiting Verification)'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='provisional', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('prerequisites_verified', models.BooleanField(default=False, verbose_name='Prerequisites Verified')),
                ('verification_notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('reference_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Reference Code')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_enrollments', to='payments.paymenttransaction', verbose_name='Payment Transaction')),
                ('programme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provisional_enrollments', to='learnerships.learnershipprogramme', verbose_name='Programme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisional_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_provisional_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Provisional Enrollment',
                'verbose_name_plural': 'Provisional Enrollments',
                'db_table': 'provisional_enrollments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='provisional_status_6cffeb_idx'), models.Index(fields=['reference_code'], name='provisional_referen_3a92e2_idx'), models.Index(fields=['user', 'status'], name='provisional_user_id_2d9765_idx')],
            },
        ),
    ]
