# Generated by Django 5.2.10 on 2026-01-16 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aicerts_courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masterclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, help_text='Auto-filled from selected courses', max_length=255)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('country_name', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('venue', models.CharField(blank=True, default='TBA', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('max_participants', models.PositiveIntegerField(default=35)),
                ('current_participants', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_courses', models.ManyToManyField(blank=True, related_name='masterclasses', to='aicerts_courses.aicertscourse', verbose_name='Linked Provider Courses')),
            ],
            options={
                'verbose_name': 'Masterclass',
                'verbose_name_plural': 'Masterclasses',
                'ordering': ['start_date', 'title'],
            },
        ),
    ]
