# Generated by Django 4.2.16 on 2026-02-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='has_online_option',
            field=models.BooleanField(default=True, help_text='Whether this masterclass can be attended online ($200 discount applies)'),
        ),
    ]
