# Generated by Django 5.2.10 on 2026-01-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0002_alter_aicertscourse_options_and_more'),
        ('masterclasses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='city',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='venue',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Select one or more African countries where this masterclass is offered', to='masterclasses.masterclass', verbose_name='Offered in African Countries'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text="List of countries with their cities: e.g. [{'country': 'ZA', 'cities': ['Johannesburg', 'Cape Town']}]"),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='category',
            field=models.CharField(blank=True, help_text='Auto-filled from selected AICERTS courses', max_length=255),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='provider_courses',
            field=models.ManyToManyField(blank=True, related_name='masterclasses', to='aicerts_courses.aicertscourse', verbose_name='Linked Provider Courses (AICERTS)'),
        ),
    ]
