# Generated by Django 5.2.10 on 2026-01-17 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0002_remove_masterclass_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='countries',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='city',
            field=models.CharField(blank=True, help_text='City where masterclass is held', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='country_code',
            field=models.CharField(blank=True, choices=[('DZ', 'Algeria'), ('AO', 'Angola'), ('BJ', 'Benin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CV', 'Cape Verde'), ('CM', 'Cameroon'), ('CF', 'Central African Republic'), ('TD', 'Chad'), ('KM', 'Comoros'), ('CG', 'Congo'), ('CD', 'Democratic Republic of the Congo'), ('CI', "Côte d'Ivoire"), ('DJ', 'Djibouti'), ('EG', 'Egypt'), ('GQ', 'Equatorial Guinea'), ('ER', 'Eritrea'), ('SZ', 'Eswatini'), ('ET', 'Ethiopia'), ('GA', 'Gabon'), ('GM', 'Gambia'), ('GH', 'Ghana'), ('GN', 'Guinea'), ('GW', 'Guinea-Bissau'), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Liberia'), ('LY', 'Libya'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritania'), ('MU', 'Mauritius'), ('MA', 'Morocco'), ('MZ', 'Mozambique'), ('NA', 'Namibia'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('RW', 'Rwanda'), ('ST', 'São Tomé and Príncipe'), ('SN', 'Senegal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalia'), ('ZA', 'South Africa'), ('SS', 'South Sudan'), ('SD', 'Sudan'), ('TZ', 'Tanzania'), ('TG', 'Togo'), ('TN', 'Tunisia'), ('UG', 'Uganda'), ('ZM', 'Zambia'), ('ZW', 'Zimbabwe')], help_text='ISO 3166-1 alpha-2 country code', max_length=2, null=True, verbose_name='Country Code'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='country_name',
            field=models.CharField(blank=True, help_text='Full country name', max_length=100, null=True, verbose_name='Country Name'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='focus_area',
            field=models.CharField(blank=True, help_text='Area of focus (e.g., AI Strategy, Blockchain Development)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='stream_type',
            field=models.CharField(choices=[('professional', 'Professional'), ('technical', 'Technical')], default='professional', help_text='Type of masterclass for filtering', max_length=20),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium')], default='standard', help_text='Tier/level of the masterclass', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='venue',
            field=models.CharField(blank=True, help_text='Specific venue or address', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='locations',
            field=models.JSONField(blank=True, default=list, help_text='Legacy field: List of countries with their cities'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in the specified currency', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
