# Generated by Django 4.2.16 on 2026-02-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0002_masterclass_has_online_option'),
        ('masterclasses', '0003_remove_masterclass_countries_masterclass_city_and_more'),
    ]

    operations = [
    ]
