# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0004_merge_20260216_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='has_online_option',
        ),
    ]
