# Generated by Django 4.2.16 on 2026-02-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0005_remove_masterclass_has_online_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='has_online_option',
            field=models.BooleanField(default=True, help_text='Whether this masterclass can be attended online ($200 discount applies)'),
        ),
    ]
