# Generated by Django 4.2.16 on 2026-03-16 07:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterclasses', '0009_update_masterclass_pricing_no_discounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='price',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to teach this masterclass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_masterclasses', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Instructor'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='has_online_option',
            field=models.BooleanField(default=True, help_text='Whether this masterclass can be attended online'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='price_online',
            field=models.DecimalField(decimal_places=2, help_text='Online attendance price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='price_physical',
            field=models.DecimalField(decimal_places=2, help_text='Physical attendance price in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
