# Generated by Django 4.2.16 on 2026-03-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterclasses', '0010_remove_masterclass_price_masterclass_instructor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
