# Generated by Django 4.2.16 on 2026-05-05 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0049_rename_enrollment_id_enrollment_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masterclasses', '0011_alter_masterclass_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterclassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('enrolled', 'Enrolled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attendance_type', models.CharField(choices=[('physical', 'Physical (On-site)'), ('online', 'Online (Virtual)')], default='online', max_length=20)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='masterclasses.masterclass')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masterclass_enrollments', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masterclass_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Masterclass Enrollment',
                'verbose_name_plural': 'Masterclass Enrollments',
                'ordering': ['-created_at'],
                'unique_together': {('masterclass', 'user')},
            },
        ),
    ]
