# Generated by Django 5.2.10 on 2026-01-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend_manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appappearance',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Null means global appearance for all users', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_appearance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='theme',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frontend_themes', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By'),
        ),
        migrations.AlterUniqueTogether(
            name='appappearance',
            unique_together={('user',)},
        ),
    ]
