# Generated by Django 4.2.16 on 2026-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_manage', '0003_add_comprehensive_theme_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appappearance',
            name='surface_variant',
            field=models.CharField(default='#21262D', help_text='Variant surface color for elevated components', max_length=7),
        ),
    ]
