# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_manage', '0004_alter_appappearance_surface_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('preset_type', models.CharField(choices=[('wp_default', 'WordPress Default (Vivid Cyan Blue)'), ('wp_vivid', 'WordPress Vivid (Orange/Red)'), ('wp_pastel', 'WordPress Pastel (Soft Colors)'), ('wp_dark', 'WordPress Dark (Dark Mode)'), ('wp_professional', 'WordPress Professional (Blue/Purple)'), ('wp_energetic', 'WordPress Energetic (Orange/Amber)'), ('wp_nature', 'WordPress Nature (Green/Cyan)'), ('custom', 'Custom Theme')], default='wp_default', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('primary_color', models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#0693E3', max_length=7)),
                ('primary_variant', models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#8ED1FC', max_length=7)),
                ('secondary_color', models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#9B51E0', max_length=7)),
                ('accent_color', models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#00D084', max_length=7)),
                ('background_color', models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#FFFFFF', max_length=7)),
                ('text_primary', models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#000000', max_length=7)),
                ('shadow_type', models.CharField(choices=[('natural', 'Natural Shadow'), ('deep', 'Deep Shadow'), ('sharp', 'Sharp Shadow'), ('outlined', 'Outlined Shadow'), ('crisp', 'Crisp Shadow')], default='natural', max_length=20)),
                ('spacing_scale', models.CharField(choices=[('s20', 'Extra Small (7px)'), ('s30', 'Small (11px)'), ('s40', 'Medium (16px)'), ('s50', 'Large (24px)'), ('s60', 'Extra Large (36px)'), ('s70', 'XX Large (54px)'), ('s80', 'XXX Large (81px)')], default='s40', max_length=20)),
                ('font_size', models.CharField(choices=[('small', 'Small (13px)'), ('medium', 'Medium (20px)'), ('large', 'Large (36px)'), ('xlarge', 'X-Large (42px)')], default='medium', max_length=20)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Theme Preset',
                'verbose_name_plural': 'Theme Presets',
                'db_table': 'frontend_theme_presets',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='app_bar_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='bottom_nav_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='card_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='divider_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='fab_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='info_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='on_background',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='on_error',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='on_primary',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='on_success',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='on_surface',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='on_warning',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='outline_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='outline_variant',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='shadow_color',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='shadow_opacity',
        ),
        migrations.RemoveField(
            model_name='appappearance',
            name='surface_variant',
        ),
        migrations.AddField(
            model_name='appappearance',
            name='accent_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#00D084', help_text='Tertiary accent/action color', max_length=7),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='border_radius',
            field=models.CharField(choices=[('none', 'No Radius'), ('small', 'Small (4px)'), ('medium', 'Medium (8px)'), ('large', 'Large (16px)'), ('full', 'Full (50%)')], default='medium', help_text='Border radius style', max_length=20),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='button_style',
            field=models.CharField(choices=[('flat', 'Flat'), ('rounded', 'Rounded'), ('pill', 'Pill'), ('outlined', 'Outlined')], default='rounded', help_text='Button style preset', max_length=20),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='error_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#CF2E2E', help_text='Error/warning color', max_length=7),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='favicon_url',
            field=models.URLField(blank=True, help_text='URL to favicon', null=True),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='font_family_secondary',
            field=models.CharField(blank=True, default='Open Sans', help_text='Secondary font family for headings', max_length=100),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='font_size_multiplier',
            field=models.FloatField(default=1.0, help_text='Font size multiplier (0.8 to 1.5)'),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='font_size_preset',
            field=models.CharField(choices=[('small', 'Small (13px)'), ('medium', 'Medium (20px)'), ('large', 'Large (36px)'), ('xlarge', 'X-Large (42px)')], default='medium', help_text='Base font size preset', max_length=20),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='logo_dark_url',
            field=models.URLField(blank=True, help_text='URL to dark mode logo', null=True),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL to main logo image', null=True),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='shadow_preset',
            field=models.CharField(choices=[('natural', 'Natural Shadow'), ('deep', 'Deep Shadow'), ('sharp', 'Sharp Shadow'), ('outlined', 'Outlined Shadow'), ('crisp', 'Crisp Shadow')], default='natural', help_text='WordPress shadow style preset', max_length=20),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='spacing_preset',
            field=models.CharField(choices=[('s20', 'Extra Small (7px)'), ('s30', 'Small (11px)'), ('s40', 'Medium (16px)'), ('s50', 'Large (24px)'), ('s60', 'Extra Large (36px)'), ('s70', 'XX Large (54px)'), ('s80', 'XXX Large (81px)')], default='s40', help_text='Base spacing unit (based on WordPress rem scale)', max_length=20),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='success_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#00D084', help_text='Success color', max_length=7),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='text_tertiary',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#ABB8C3', help_text='Tertiary/hint text color', max_length=7),
        ),
        migrations.AddField(
            model_name='appappearance',
            name='warning_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#FCB900', help_text='Warning color', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='background_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#FFFFFF', help_text='Main background color', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='font_family',
            field=models.CharField(blank=True, default='Roboto', help_text='Primary font family (Google Font name)', max_length=100),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='is_dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode theme'),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='primary_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#0693E3', help_text='Main brand color from WordPress palette', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='primary_variant',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#8ED1FC', help_text='Lighter variant of primary color', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='secondary_color',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#9B51E0', help_text='Secondary accent color', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='surface_color',
            field=models.CharField(default='#F5F5F7', help_text='Cards, sheets, dialogs background', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='text_primary',
            field=models.CharField(choices=[('#000000', 'Black'), ('#ABB8C3', 'Cyan Bluish Gray'), ('#FFFFFF', 'White'), ('#F78DA7', 'Pale Pink'), ('#CF2E2E', 'Vivid Red'), ('#FF6900', 'Luminous Vivid Orange'), ('#FCB900', 'Luminous Vivid Amber'), ('#7BDCB5', 'Light Green Cyan'), ('#00D084', 'Vivid Green Cyan'), ('#8ED1FC', 'Pale Cyan Blue'), ('#0693E3', 'Vivid Cyan Blue'), ('#9B51E0', 'Vivid Purple')], default='#000000', help_text='Primary text color', max_length=7),
        ),
        migrations.AlterField(
            model_name='appappearance',
            name='text_secondary',
            field=models.CharField(default='#666666', help_text='Secondary text/muted color', max_length=7),
        ),
    ]
