# Generated by Django 4.2.16 on 2026-01-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Server name for identification', max_length=255)),
                ('api_url', models.URLField(help_text='BBB API base URL (e.g., https://bbb.example.com/bigbluebutton/api/)')),
                ('secret', models.CharField(help_text='BBB server secret key', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Is this server available for new sessions')),
                ('max_load', models.IntegerField(default=100, help_text='Maximum concurrent sessions')),
                ('current_load', models.IntegerField(default=0, help_text='Current active sessions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BBB Server',
                'verbose_name_plural': 'BBB Servers',
                'db_table': 'bbb_servers',
            },
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(editable=False, max_length=255, unique=True)),
                ('meeting_id', models.CharField(help_text='BBB meeting ID', max_length=255, unique=True)),
                ('course_id', models.IntegerField(help_text='Course ID (generic reference)')),
                ('course_type', models.CharField(default='course', help_text='Type: course, masterclass, learnership', max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Session description or agenda')),
                ('scheduled_start', models.DateTimeField(help_text='Scheduled start time')),
                ('scheduled_end', models.DateTimeField(help_text='Scheduled end time')),
                ('actual_start', models.DateTimeField(blank=True, help_text='Actual start time', null=True)),
                ('actual_end', models.DateTimeField(blank=True, help_text='Actual end time', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('moderator_password', models.CharField(editable=False, max_length=255)),
                ('attendee_password', models.CharField(editable=False, max_length=255)),
                ('record', models.BooleanField(default=True, help_text='Record this session')),
                ('auto_start_recording', models.BooleanField(default=True, help_text='Start recording automatically')),
                ('max_participants', models.IntegerField(default=100, help_text='Maximum participants')),
                ('allow_start_stop_recording', models.BooleanField(default=True)),
                ('has_recording', models.BooleanField(default=False, help_text='Recording is available')),
                ('welcome_message', models.TextField(blank=True, help_text='Welcome message shown when joining')),
                ('logout_url', models.URLField(blank=True, help_text='Redirect URL after leaving session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bbb_server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='bbb_integration.bbbserver')),
                ('instructor', models.ForeignKey(help_text='Session instructor/moderator', on_delete=django.db.models.deletion.CASCADE, related_name='taught_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Live Session',
                'verbose_name_plural': 'Live Sessions',
                'db_table': 'live_sessions',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='SessionRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(help_text='BBB recording ID', max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('published', models.BooleanField(default=False, help_text='Is recording published/visible')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Recording duration in minutes')),
                ('playback_url', models.URLField(help_text='BBB playback URL')),
                ('playback_format', models.CharField(default='presentation', help_text='Format: presentation, video', max_length=50)),
                ('size_bytes', models.BigIntegerField(default=0, help_text='Recording file size in bytes')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Recording thumbnail', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional recording metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='bbb_integration.livesession')),
            ],
            options={
                'verbose_name': 'Session Recording',
                'verbose_name_plural': 'Session Recordings',
                'db_table': 'session_recordings',
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['session', 'published'], name='session_rec_session_e4636e_idx'), models.Index(fields=['start_time'], name='session_rec_start_t_164069_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=0, help_text='Time spent in session (minutes)')),
                ('joined_as_moderator', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='bbb_integration.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session Attendance',
                'verbose_name_plural': 'Session Attendances',
                'db_table': 'session_attendances',
                'indexes': [models.Index(fields=['session', 'user'], name='session_att_session_7a0fab_idx'), models.Index(fields=['user', 'joined_at'], name='session_att_user_id_dc55aa_idx')],
                'unique_together': {('session', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'scheduled_start'], name='live_sessio_status_035d02_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['instructor', 'status'], name='live_sessio_instruc_cd5832_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['course_id', 'course_type'], name='live_sessio_course__17a2af_idx'),
        ),
    ]
