# Generated by Django 5.2.10 on 2026-03-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbb_integration', '0003_sessioninvitation'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sessioninvitation',
            new_name='session_inv_session_50e17a_idx',
            old_name='bbb_session_session_3c9f0f_idx',
        ),
        migrations.RenameIndex(
            model_name='sessioninvitation',
            new_name='session_inv_email_f34578_idx',
            old_name='bbb_session_email_s_e5c1e7_idx',
        ),
        migrations.RenameIndex(
            model_name='sessioninvitation',
            new_name='session_inv_invitat_53580f_idx',
            old_name='bbb_session_invitat_6c7d79_idx',
        ),
        migrations.AlterField(
            model_name='sessioninvitation',
            name='invitation_token',
            field=models.CharField(editable=False, max_length=255, unique=True),
        ),
    ]
