# Generated by Django 4.2.16 on 2026-02-01 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aicerts_courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICertsSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('course_sync', 'Course Data Sync'), ('user_create', 'User Creation'), ('user_enroll', 'User Enrollment'), ('user_auth', 'User Authentication'), ('progress_update', 'Progress Update'), ('instructor_sync', 'Instructor Sync')], help_text='Type of sync operation', max_length=50)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], help_text='Operation outcome', max_length=20)),
                ('request_data', models.JSONField(blank=True, default=dict, help_text='API request parameters (excluding sensitive data)')),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='API response data')),
                ('error_message', models.TextField(blank=True, help_text='Error details if operation failed', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='API call duration in milliseconds', null=True)),
                ('records_processed', models.IntegerField(default=0, help_text='Number of records processed (for bulk operations)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, help_text='Course involved in operation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='aicerts_courses.aicertscourse')),
                ('user', models.ForeignKey(blank=True, help_text='User involved in operation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aicerts_sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AICERTs Sync Log',
                'verbose_name_plural': 'AICERTs Sync Logs',
                'db_table': 'aicerts_sync_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operation_type', 'status', '-created_at'], name='aicerts_syn_operati_c787d1_idx'), models.Index(fields=['user', '-created_at'], name='aicerts_syn_user_id_e1b4bb_idx'), models.Index(fields=['course', '-created_at'], name='aicerts_syn_course__51e685_idx')],
            },
        ),
        migrations.CreateModel(
            name='AICertsSSOSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sso_url', models.TextField(help_text='Generated SSO URL (signature excluded for security)')),
                ('session_token', models.CharField(help_text='Unique token for this SSO session', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address", null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User's browser/device information", null=True)),
                ('successful', models.BooleanField(default=False, help_text='Was SSO authentication successful?')),
                ('accessed_at', models.DateTimeField(blank=True, help_text='When user accessed AICERTs via SSO', null=True)),
                ('expires_at', models.DateTimeField(help_text='When SSO session expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='Target course (if SSO was for specific course)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_sessions', to='aicerts_courses.aicertscourse')),
                ('user', models.ForeignKey(help_text='User who initiated SSO', on_delete=django.db.models.deletion.CASCADE, related_name='aicerts_sso_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AICERTs SSO Session',
                'verbose_name_plural': 'AICERTs SSO Sessions',
                'db_table': 'aicerts_sso_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='aicerts_sso_user_id_ac4481_idx'), models.Index(fields=['session_token'], name='aicerts_sso_session_4824a4_idx'), models.Index(fields=['successful', '-created_at'], name='aicerts_sso_success_5ee531_idx')],
            },
        ),
        migrations.CreateModel(
            name='AICertsInstructorDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aicerts_instructor_id', models.PositiveIntegerField(help_text="Instructor's user ID on AICERTs LMS")),
                ('designated_at', models.DateTimeField(auto_now_add=True, help_text='When instructor was designated for this course')),
                ('is_active', models.BooleanField(default=True, help_text='Is this designation currently active?')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this designation', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='Course instructor is authorized to teach', on_delete=django.db.models.deletion.CASCADE, related_name='instructor_designations', to='aicerts_courses.aicertscourse')),
                ('designated_by', models.ForeignKey(blank=True, help_text='Admin who made this designation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aicerts_designations_made', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(help_text='AICERTs-registered instructor', limit_choices_to={'is_aicerts_instructor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='aicerts_designations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AICERTs Instructor Designation',
                'verbose_name_plural': 'AICERTs Instructor Designations',
                'db_table': 'aicerts_instructor_designations',
                'ordering': ['-designated_at'],
                'indexes': [models.Index(fields=['instructor', 'is_active'], name='aicerts_ins_instruc_7567c6_idx'), models.Index(fields=['course', 'is_active'], name='aicerts_ins_course__23312d_idx')],
                'unique_together': {('instructor', 'course')},
            },
        ),
        migrations.CreateModel(
            name='AICertsEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aicerts_enrollment_status', models.CharField(choices=[('pending', 'Pending Sync'), ('enrolled', 'Enrolled on AICERTs'), ('failed', 'Sync Failed'), ('unenrolled', 'Unenrolled')], default='pending', help_text='Synchronization status with AICERTs', max_length=20)),
                ('aicerts_already_enrolled', models.BooleanField(default=False, help_text='Was user already enrolled when we tried to enroll?')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, help_text='When user enrolled on Hosi Academy')),
                ('synced_at', models.DateTimeField(blank=True, help_text='When enrollment was synced to AICERTs', null=True)),
                ('last_sync_attempt', models.DateTimeField(blank=True, help_text='Last attempted sync (for retry tracking)', null=True)),
                ('sync_attempts', models.IntegerField(default=0, help_text='Number of sync attempts')),
                ('sync_error', models.TextField(blank=True, help_text='Error message from last sync attempt', null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Course completion percentage (0-100)', max_digits=5)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time user accessed course on AICERTs', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When user completed the course', null=True)),
                ('certificate_issued_at', models.DateTimeField(blank=True, help_text='When certificate was issued', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(help_text='AICERTs course', on_delete=django.db.models.deletion.CASCADE, related_name='hosi_enrollments', to='aicerts_courses.aicertscourse')),
                ('user', models.ForeignKey(help_text='Hosi Academy user', on_delete=django.db.models.deletion.CASCADE, related_name='aicerts_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AICERTs Enrollment',
                'verbose_name_plural': 'AICERTs Enrollments',
                'db_table': 'aicerts_enrollments',
                'ordering': ['-enrolled_at'],
                'indexes': [models.Index(fields=['user', 'aicerts_enrollment_status'], name='aicerts_enr_user_id_482976_idx'), models.Index(fields=['course', 'aicerts_enrollment_status'], name='aicerts_enr_course__b21e6a_idx'), models.Index(fields=['aicerts_enrollment_status', 'last_sync_attempt'], name='aicerts_enr_aicerts_189da5_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
