# Generated by Django 5.2.10 on 2026-01-16 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('frontend_manage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="ISO 3166-1 alpha-2 code, e.g., 'ZA', 'NG', 'KE'", max_length=2, unique=True)),
                ('name', models.CharField(help_text='Full country name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'localization_countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="ISO 639-1 or 639-2 language code (e.g., 'sw' for Swahili, 'yo' for Yorùbá)", max_length=191, unique=True)),
                ('name', models.CharField(help_text='English name of the language', max_length=191)),
                ('native', models.CharField(help_text="Name in the native language (e.g., 'Kiswahili', 'Èdè Yorùbá')", max_length=191)),
                ('rtl', models.SmallIntegerField(choices=[(0, 'Left-to-Right'), (1, 'Right-to-Left')], default=0, help_text='1 = Right-to-Left (e.g., Arabic, Geʽez for Amharic/Tigrinya)')),
                ('status', models.SmallIntegerField(choices=[(0, 'Disabled'), (1, 'Active')], default=1, help_text='Is this language available in the LMS?')),
                ('json_exist', models.SmallIntegerField(choices=[(0, 'Missing'), (1, 'Translation files present')], default=0, help_text='Do translation JSON files exist for this language?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'db_table': 'languages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_message', models.CharField(blank=True, help_text="Country-specific greeting (e.g., 'Sawubona!' for ZA)", max_length=200)),
                ('holiday_banner_url', models.URLField(blank=True, help_text='Banner for national holidays (e.g., Youth Day image for ZA)')),
                ('holiday_date', models.DateField(blank=True, help_text='Primary national holiday date (e.g., 16 June for ZA)', null=True)),
                ('cultural_note', models.TextField(blank=True, help_text="Brief note on cultural elements (e.g., 'Celebrate African Unity!')")),
                ('is_default', models.BooleanField(default=False, help_text='Use this as fallback when no country is detected')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appearance', models.ForeignKey(blank=True, help_text='Optional color/mode override for this country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend_manage.appappearance')),
                ('country', models.OneToOneField(help_text='One override per country', on_delete=django.db.models.deletion.CASCADE, related_name='override', to='localization.country')),
                ('default_language', models.ForeignKey(blank=True, help_text='Recommended default language for this country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.language')),
            ],
            options={
                'verbose_name': 'Country Override',
                'verbose_name_plural': 'Country Overrides',
                'db_table': 'localization_country_overrides',
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Unique key, e.g., 'welcome_message'", max_length=191)),
                ('value', models.TextField(help_text='Translated text, supports placeholders')),
                ('description', models.TextField(blank=True, help_text='Context for translators')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='localization.language')),
            ],
            options={
                'verbose_name': 'Translation',
                'verbose_name_plural': 'Translations',
                'db_table': 'localization_translations',
                'unique_together': {('key', 'language')},
            },
        ),
    ]
