# Generated by Django 4.2.16 on 2026-01-28 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Holiday name in English (e.g., 'Eid al-Fitr', 'Christmas Day')", max_length=200)),
                ('native_name', models.CharField(blank=True, help_text='Holiday name in native language', max_length=200)),
                ('holiday_type', models.CharField(choices=[('national', 'National Holiday'), ('religious_christian', 'Christian Holiday'), ('religious_muslim', 'Muslim Holiday'), ('religious_jewish', 'Jewish Holiday'), ('religious_traditional', 'Traditional African Religion'), ('cultural', 'Cultural Celebration'), ('historical', 'Historical Commemoration'), ('seasonal', 'Seasonal Festival')], help_text='Type of holiday', max_length=50)),
                ('is_fixed_date', models.BooleanField(default=True, help_text='True for fixed dates (e.g., Jan 1), False for lunar/variable dates (e.g., Eid)')),
                ('month', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], help_text='Month (1-12) for fixed date holidays', null=True)),
                ('day', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31)], help_text='Day (1-31) for fixed date holidays', null=True)),
                ('year_dates', models.JSONField(blank=True, default=dict, help_text="Variable dates by year: {'2024': '2024-04-10', '2025': '2025-03-30', ...}")),
                ('duration_days', models.IntegerField(default=1, help_text='Number of days for this holiday (e.g., 2 for Eid)')),
                ('description', models.TextField(blank=True, help_text='Description and significance of this holiday')),
                ('is_public_holiday', models.BooleanField(default=True, help_text='Is this an official public holiday (banks/schools closed)?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Country this holiday belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='localization.country')),
            ],
            options={
                'verbose_name': 'Public Holiday',
                'verbose_name_plural': 'Public Holidays',
                'db_table': 'public_holidays',
                'ordering': ['country__name', 'month', 'day'],
            },
        ),
        migrations.CreateModel(
            name='LocalizedGreeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_greeting', models.CharField(help_text="Greeting in native/indigenous language (e.g., 'Jambo', 'Sawubona', 'Snnuu')", max_length=200)),
                ('international_greeting', models.CharField(help_text="Greeting in international language (e.g., 'Hello', 'Bonjour', 'Olá')", max_length=200)),
                ('welcome_message', models.TextField(help_text='Full welcome message combining both languages')),
                ('time_of_day', models.CharField(choices=[('morning', 'Morning (00:00 - 11:59)'), ('afternoon', 'Afternoon (12:00 - 17:59)'), ('evening', 'Evening (18:00 - 23:59)'), ('any', 'Any time of day')], default='any', help_text='When to show this greeting', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority greetings are shown first (holiday greetings should have high priority)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(help_text='Country this greeting is for', on_delete=django.db.models.deletion.CASCADE, related_name='greetings', to='localization.country')),
                ('holiday', models.ForeignKey(blank=True, help_text='Link to specific holiday (leave blank for general greeting)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greetings', to='localization.publicholiday')),
                ('international_language', models.ForeignKey(help_text='International language (English, French, Portuguese, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='international_greetings', to='localization.language')),
                ('native_language', models.ForeignKey(help_text='Which native language this greeting is in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='native_greetings', to='localization.language')),
            ],
            options={
                'verbose_name': 'Localized Greeting',
                'verbose_name_plural': 'Localized Greetings',
                'db_table': 'localized_greetings',
                'ordering': ['-priority', 'country__name'],
            },
        ),
        migrations.CreateModel(
            name='HolidayMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='Message to display (can include HTML)')),
                ('native_language_message', models.TextField(blank=True, help_text='Message in native language (optional)')),
                ('show_banner', models.BooleanField(default=True, help_text='Show as banner/alert?')),
                ('banner_color', models.CharField(default='#4CAF50', help_text='Banner background color (hex code)', max_length=7)),
                ('banner_icon', models.CharField(blank=True, help_text="Icon name (e.g., 'celebration', 'mosque', 'church')", max_length=50)),
                ('show_days_before', models.IntegerField(default=0, help_text='Start showing this many days before the holiday')),
                ('show_days_after', models.IntegerField(default=0, help_text='Keep showing this many days after the holiday')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Localization admin who created this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holiday_messages', to=settings.AUTH_USER_MODEL)),
                ('holiday', models.ForeignKey(help_text='Holiday this message is for', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='localization.publicholiday')),
            ],
            options={
                'verbose_name': 'Holiday Message',
                'verbose_name_plural': 'Holiday Messages',
                'db_table': 'holiday_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfricanCountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('north', 'North Africa'), ('west', 'West Africa'), ('east', 'East Africa'), ('central', 'Central Africa'), ('southern', 'Southern Africa')], help_text='African region', max_length=50)),
                ('timezone', models.CharField(default='Africa/Johannesburg', help_text="Primary timezone (e.g., 'Africa/Nairobi', 'Africa/Lagos')", max_length=50)),
                ('cultural_values', models.TextField(blank=True, help_text="Key cultural values (e.g., 'Ubuntu', 'Harambee', 'Sankofa')")),
                ('dominant_religions', models.JSONField(blank=True, default=list, help_text="List of major religions (e.g., ['Christianity', 'Islam', 'Traditional'])")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colonial_language', models.ForeignKey(blank=True, help_text='Primary colonial/international language (English, French, Portuguese, etc.)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colonial_countries', to='localization.language')),
                ('country', models.OneToOneField(help_text='Link to country', on_delete=django.db.models.deletion.CASCADE, related_name='african_profile', to='localization.country')),
                ('native_languages', models.ManyToManyField(help_text='Indigenous/pre-colonial languages (e.g., Swahili, Yoruba, Zulu)', related_name='native_countries', to='localization.language')),
            ],
            options={
                'verbose_name': 'African Country Profile',
                'verbose_name_plural': 'African Country Profiles',
                'db_table': 'african_country_profiles',
                'ordering': ['country__name'],
            },
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['country', 'month', 'day'], name='public_holi_country_c7cf7c_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['country', 'holiday_type'], name='public_holi_country_ba1191_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedgreeting',
            index=models.Index(fields=['country', 'time_of_day'], name='localized_g_country_ab2e82_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedgreeting',
            index=models.Index(fields=['country', 'holiday'], name='localized_g_country_356bc4_idx'),
        ),
        migrations.AddIndex(
            model_name='localizedgreeting',
            index=models.Index(fields=['country', '-priority'], name='localized_g_country_ba6420_idx'),
        ),
    ]
