# Generated by Django 4.2.16 on 2026-01-28 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('localization', '0002_publicholiday_localizedgreeting_holidaymessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalizedPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Promotion title (e.g., '50% Off AI Courses')", max_length=200)),
                ('native_title', models.CharField(blank=True, help_text='Title in native language', max_length=200)),
                ('description', models.TextField(help_text='Promotion description and details')),
                ('native_description', models.TextField(blank=True, help_text='Description in native language')),
                ('promotion_type', models.CharField(choices=[('discount', 'Discount/Sale'), ('free_course', 'Free Course'), ('bundle', 'Bundle Offer'), ('limited_time', 'Limited Time Offer'), ('seasonal', 'Seasonal Campaign'), ('partnership', 'Partnership Offer'), ('referral', 'Referral Program'), ('other', 'Other')], default='discount', max_length=50)),
                ('image_url', models.URLField(blank=True, help_text='Promotion banner image URL')),
                ('background_color', models.CharField(default='#FF5722', help_text='Banner background color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color (hex code)', max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon/emoji for promotion (e.g., '🎉', '💰', '🎓')", max_length=50)),
                ('cta_text', models.CharField(default='Learn More', help_text='Call-to-action button text', max_length=100)),
                ('cta_url', models.URLField(blank=True, help_text='Link when user clicks the promotion')),
                ('start_date', models.DateField(help_text='Promotion starts on this date')),
                ('end_date', models.DateField(help_text='Promotion ends on this date')),
                ('priority', models.IntegerField(default=0, help_text='Higher priority promotions show first (0-100)')),
                ('show_on_splash', models.BooleanField(default=False, help_text='Show on splash screen')),
                ('show_on_home', models.BooleanField(default=True, help_text='Show on home page')),
                ('show_on_onboarding', models.BooleanField(default=True, help_text='Show during onboarding')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(help_text='Countries where this promotion is visible', related_name='promotions', to='localization.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localized Promotion',
                'verbose_name_plural': 'Localized Promotions',
                'db_table': 'localized_promotions',
                'ordering': ['-priority', '-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='localized_p_start_d_ada0ff_idx'), models.Index(fields=['-priority'], name='localized_p_priorit_e6f04d_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalizedAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Announcement title', max_length=200)),
                ('native_title', models.CharField(blank=True, help_text='Title in native language', max_length=200)),
                ('message', models.TextField(help_text='Announcement message')),
                ('native_message', models.TextField(blank=True, help_text='Message in native language')),
                ('announcement_type', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('success', 'Success/Good News'), ('update', 'Platform Update'), ('maintenance', 'Maintenance'), ('partnership', 'Partnership Announcement'), ('new_feature', 'New Feature'), ('event', 'Event Announcement')], default='info', max_length=50)),
                ('icon', models.CharField(blank=True, help_text="Icon/emoji (e.g., 'ℹ️', '⚠️', '✅', '📢')", max_length=50)),
                ('background_color', models.CharField(default='#2196F3', help_text='Background color (hex code)', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', help_text='Text color (hex code)', max_length=7)),
                ('action_text', models.CharField(blank=True, help_text="Optional action button text (e.g., 'Learn More', 'View Details')", max_length=100)),
                ('action_url', models.URLField(blank=True, help_text='Optional link for action button')),
                ('start_date', models.DateField(help_text='Show announcement starting from this date')),
                ('end_date', models.DateField(blank=True, help_text='Stop showing after this date (leave empty for indefinite)', null=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority announcements show first (0-100)')),
                ('show_on_splash', models.BooleanField(default=False, help_text='Show on splash screen')),
                ('show_on_onboarding', models.BooleanField(default=True, help_text='Show during onboarding (pop-up)')),
                ('show_on_home', models.BooleanField(default=True, help_text='Show on home page')),
                ('is_dismissible', models.BooleanField(default=True, help_text='Can user dismiss this announcement?')),
                ('require_acknowledgment', models.BooleanField(default=False, help_text='Require user to acknowledge before dismissing')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('countries', models.ManyToManyField(blank=True, help_text='Countries where visible (leave empty for all countries)', related_name='announcements', to='localization.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Localized Announcement',
                'verbose_name_plural': 'Localized Announcements',
                'db_table': 'localized_announcements',
                'ordering': ['-priority', '-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='localized_a_start_d_618c21_idx'), models.Index(fields=['-priority'], name='localized_a_priorit_182fe3_idx')],
            },
        ),
    ]
