# Generated by Django 4.2.16 on 2026-01-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0003_localizedpromotion_localizedannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='localizedannouncement',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload announcement banner image', null=True, upload_to='announcements/'),
        ),
        migrations.AddField(
            model_name='localizedpromotion',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload promotion banner image', null=True, upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='localizedpromotion',
            name='image_url',
            field=models.URLField(blank=True, help_text='Or provide external image URL'),
        ),
    ]
