# Generated by Django 4.2.16 on 2026-01-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0004_localizedannouncement_image_localizedpromotion_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="State/Region/Province name (e.g., 'Gauteng', 'Lagos State', 'Nairobi County')", max_length=100)),
                ('code', models.CharField(blank=True, help_text="State code if applicable (e.g., 'GT', 'LA')", max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(help_text='Country this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='localization.country')),
            ],
            options={
                'verbose_name': 'State/Region',
                'verbose_name_plural': 'States/Regions',
                'db_table': 'localization_states',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="City name (e.g., 'Johannesburg', 'Lagos', 'Nairobi')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('population', models.IntegerField(blank=True, help_text='City population (optional, for sorting)', null=True)),
                ('country', models.ForeignKey(help_text='Country this city belongs to (denormalized for quick access)', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.country')),
                ('state', models.ForeignKey(help_text='State this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.state')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'localization_cities',
                'ordering': ['country', 'state', 'name'],
                'unique_together': {('state', 'name')},
            },
        ),
    ]
