# Generated by Django 4.2.16 on 2026-02-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0005_state_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, help_text="Country phone calling code (e.g., '+27')", max_length=10, null=True),
        ),
    ]
