# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0006_country_phone_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.RemoveField(
            model_name='holidaymessage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='holidaymessage',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='localizedannouncement',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='localizedannouncement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='localizedgreeting',
            name='country',
        ),
        migrations.RemoveField(
            model_name='localizedgreeting',
            name='holiday',
        ),
        migrations.RemoveField(
            model_name='localizedgreeting',
            name='international_language',
        ),
        migrations.RemoveField(
            model_name='localizedgreeting',
            name='native_language',
        ),
        migrations.RemoveField(
            model_name='localizedpromotion',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='localizedpromotion',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='publicholiday',
            name='country',
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
        migrations.DeleteModel(
            name='AfricanCountryProfile',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='HolidayMessage',
        ),
        migrations.DeleteModel(
            name='LocalizedAnnouncement',
        ),
        migrations.DeleteModel(
            name='LocalizedGreeting',
        ),
        migrations.DeleteModel(
            name='LocalizedPromotion',
        ),
        migrations.DeleteModel(
            name='PublicHoliday',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
