# Generated by Django 4.2.16 on 2026-02-17 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0007_alter_city_unique_together_remove_city_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Province/State/Region name', max_length=100)),
                ('code', models.CharField(blank=True, help_text="Optional province code (e.g., 'GP' for Gauteng)", max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(help_text='Country this province belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='provinces', to='localization.country')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Provinces',
                'db_table': 'localization_provinces',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='City/Town name', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('population', models.IntegerField(blank=True, help_text='Approximate population (for sorting/prioritization)', null=True)),
                ('province', models.ForeignKey(help_text='Province this city belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.province')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'localization_cities',
                'ordering': ['province', '-population', 'name'],
                'unique_together': {('province', 'name')},
            },
        ),
    ]
