# Generated by Django 4.2.16 on 2026-02-18 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0008_province_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['state', '-population', 'name'], 'verbose_name': 'City', 'verbose_name_plural': 'Cities'},
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='State/Province/Region name', max_length=100)),
                ('code', models.CharField(blank=True, help_text="Optional state code (e.g., 'GP' for Gauteng)", max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(help_text='Country this state belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='localization.country')),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'localization_states',
                'ordering': ['country', 'name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(blank=True, help_text='State this city belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='localization.state'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
        migrations.RemoveField(
            model_name='city',
            name='province',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
    ]
