# Generated by Django 4.2.16 on 2026-04-23 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('SVG', 'SVG')], max_length=10)),
                ('file', models.FileField(upload_to='marketing/assets/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='marketing/thumbnails/')),
                ('suggested_caption', models.TextField(blank=True, help_text='Suggested text for social media posts')),
                ('total_clicks', models.IntegerField(default=0)),
                ('total_shares', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketing Asset',
                'verbose_name_plural': 'Marketing Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialShareEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram')], max_length=20)),
                ('referral_link', models.URLField(max_length=500)),
                ('clicks', models.IntegerField(default=0)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_events', to='marketing.marketingasset')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Social Share Event',
                'verbose_name_plural': 'Social Share Events',
                'ordering': ['-shared_at'],
            },
        ),
    ]
