# Generated by Django 4.2.16 on 2026-04-30 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=50)),
                ('object_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('goals', models.TextField(verbose_name='Primary Goals')),
                ('professional_status', models.CharField(max_length=255)),
                ('planned_start', models.CharField(max_length=100)),
                ('expectations', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Marketing Lead',
                'verbose_name_plural': 'Marketing Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
