# Generated by Django 5.2.10 on 2026-01-23 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bulk_code', models.CharField(max_length=50, unique=True, verbose_name='Bulk Enrollment Code')),
                ('enrollment_type', models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry-Based Training'), ('role_training', 'Role-Based Training')], max_length=20, verbose_name='Enrollment Type')),
                ('object_id', models.PositiveIntegerField()),
                ('total_learners', models.PositiveIntegerField(verbose_name='Total Learners')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='Currency')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Person Name')),
                ('contact_email', models.EmailField(max_length=255, verbose_name='Contact Person Email')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Contact Person Phone')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_enrollments', to='organizations.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('masterclass', 'learnershipprogramme', 'aicertscourse', 'offering')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bulk_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_enrollments', to='payments.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Bulk Enrollment',
                'verbose_name_plural': 'Bulk Enrollments',
                'db_table': 'bulk_enrollments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='bulk_enroll_company_9523c9_idx'), models.Index(fields=['bulk_code'], name='bulk_enroll_bulk_co_648c20_idx'), models.Index(fields=['content_type', 'object_id'], name='bulk_enroll_content_289f67_idx')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry-Based Training'), ('role_training', 'Role-Based Training')], max_length=20, verbose_name='Enrollment Type')),
                ('object_id', models.PositiveIntegerField()),
                ('enrollment_code', models.CharField(help_text='Unique enrollment reference code', max_length=50, unique=True, verbose_name='Enrollment Code')),
                ('status', models.CharField(choices=[('pending_info', 'Pending Information'), ('pending_payment', 'Pending Payment'), ('payment_processing', 'Payment Processing'), ('enrolled', 'Enrolled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending_info', max_length=20, verbose_name='Status')),
                ('learner_full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('learner_email', models.EmailField(max_length=255, verbose_name='Email')),
                ('learner_phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('learner_id_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID/Passport Number')),
                ('learner_address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('learner_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('learner_country', models.CharField(max_length=100, verbose_name='Country')),
                ('learner_postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('current_occupation', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Occupation')),
                ('education_level', models.CharField(blank=True, max_length=100, null=True, verbose_name='Highest Education Level')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institution/Company')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact Name')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency Contact Phone')),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship to Emergency Contact')),
                ('dietary_requirements', models.TextField(blank=True, help_text='Any dietary restrictions or allergies', null=True, verbose_name='Dietary Requirements')),
                ('accessibility_needs', models.TextField(blank=True, help_text='Any accessibility requirements', null=True, verbose_name='Accessibility Needs')),
                ('additional_notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('enrollment_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Enrollment Fee')),
                ('currency', models.CharField(default='USD', max_length=5, verbose_name='Currency')),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Discount Applied')),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Final Amount')),
                ('enrollment_data', models.JSONField(blank=True, default=dict, help_text='Additional enrollment metadata', verbose_name='Enrollment Data')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('terms_accepted', models.BooleanField(default=False, verbose_name='Terms & Conditions Accepted')),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms Accepted At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('enrolled_at', models.DateTimeField(blank=True, null=True, verbose_name='Enrolled At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('company', models.ForeignKey(blank=True, help_text='Company paying for this enrollment (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='organizations.company', verbose_name='Company')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('masterclass', 'learnershipprogramme', 'aicertscourse', 'offering')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='payments.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='enrollments_user_id_b5f69f_idx'), models.Index(fields=['company', 'status'], name='enrollments_company_a3651c_idx'), models.Index(fields=['enrollment_type', 'status'], name='enrollments_enrollm_3f6db6_idx'), models.Index(fields=['enrollment_code'], name='enrollments_enrollm_6ecab5_idx'), models.Index(fields=['content_type', 'object_id'], name='enrollments_content_e0ee14_idx')],
            },
        ),
    ]
