# Generated by Django 5.2.10 on 2026-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_bulkenrollment_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='learner_dob',
            field=models.CharField(blank=True, help_text='Format: YYYY-MM-DD', max_length=20, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='learner_gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=50, null=True, verbose_name='Gender'),
        ),
    ]
