# Generated by Django 4.2.16 on 2026-02-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_enrollment_learner_dob_enrollment_learner_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_address',
            field=models.TextField(blank=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='enrollment_type',
            field=models.CharField(blank=True, choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry', 'Industry Training'), ('custom_selection', 'Custom Selection')], help_text='Type of enrollment this payment is for', max_length=20, verbose_name='Enrollment Type'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='individual_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Individual Email'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='individual_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Individual Name'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='individual_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Individual Phone'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='Whether this is a corporate/company payment', verbose_name='Corporate Payment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='VAT/Tax Number'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['is_corporate', 'created_at'], name='payment_tra_is_corp_83b0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['enrollment_type', 'status'], name='payment_tra_enrollm_3a6b75_idx'),
        ),
    ]
