# Generated by Django 4.2.16 on 2026-02-04 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_paymenttransaction_company_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, help_text='Unique payment reference (e.g., HOSI-MCLASS-20270204-001)', max_length=50, unique=True, verbose_name='Reference Number')),
                ('training_type', models.CharField(help_text='masterclass, learnership, industry_training, custom_selection', max_length=50, verbose_name='Training Type')),
                ('training_id', models.IntegerField(help_text='ID of the training program', verbose_name='Training ID')),
                ('training_title', models.CharField(max_length=255, verbose_name='Training Title')),
                ('training_date', models.DateField(blank=True, help_text='When the training begins (if applicable)', null=True, verbose_name='Training Start Date')),
                ('learner_name', models.CharField(max_length=255, verbose_name='Learner Name')),
                ('learner_email', models.EmailField(max_length=254, verbose_name='Learner Email')),
                ('learner_phone', models.CharField(max_length=20, verbose_name='Learner Phone')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('payment_deadline', models.DateTimeField(help_text='7 working days from generation OR before training start date', verbose_name='Payment Deadline')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Payment Received'), ('verified', 'Payment Verified'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('company_name', models.CharField(blank=True, max_length=255, verbose_name='Company Name')),
                ('company_registration', models.CharField(blank=True, max_length=100, verbose_name='Company Registration Number')),
                ('company_tax_number', models.CharField(blank=True, max_length=100, verbose_name='Tax/VAT Number')),
                ('company_address', models.TextField(blank=True, verbose_name='Company Address')),
                ('company_postal_code', models.CharField(blank=True, max_length=20, verbose_name='Postal Code')),
                ('billing_contact_name', models.CharField(blank=True, max_length=255, verbose_name='Billing Contact Name')),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Billing Contact Email')),
                ('billing_contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Billing Contact Phone')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional payment reference data', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Payment Reference',
                'verbose_name_plural': 'Payment References',
                'db_table': 'payment_references',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['reference'], name='payment_ref_referen_204663_idx'), models.Index(fields=['status', 'payment_deadline'], name='payment_ref_status_9124ea_idx'), models.Index(fields=['learner_email'], name='payment_ref_learner_cf33bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('payment_admin', 'Payment Admin'), ('hr_admin', 'HR Admin'), ('executive_admin', 'Executive Admin')], max_length=50, verbose_name='Role Type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this admin role is currently active', verbose_name='Active')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Additional role-specific permissions', verbose_name='Custom Permissions')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Revoked At')),
                ('revocation_reason', models.TextField(blank=True, verbose_name='Revocation Reason')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='Revoked By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_roles', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Admin Role',
                'verbose_name_plural': 'Admin Roles',
                'db_table': 'admin_roles',
                'ordering': ['role_type', 'user'],
                'indexes': [models.Index(fields=['user', 'role_type', 'is_active'], name='admin_roles_user_id_f16e6c_idx')],
                'unique_together': {('user', 'role_type')},
            },
        ),
    ]
