# Generated by Django 4.2.16 on 2026-02-10 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentreference_adminrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkenrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry-Based Training'), ('role_training', 'Role-Based Training'), ('custom_selection', 'Custom Course Selection')], max_length=20, verbose_name='Enrollment Type'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('GNF', 'Guinean Franc'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='countrypaymentlandscape',
            name='local_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('GNF', 'Guinean Franc'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], max_length=5, verbose_name='Local Currency'),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('GNF', 'Guinean Franc'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry-Based Training'), ('role_training', 'Role-Based Training'), ('custom_selection', 'Custom Course Selection')], max_length=20, verbose_name='Enrollment Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('GNF', 'Guinean Franc'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymentreference',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('GNF', 'Guinean Franc'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('GNF', 'Guinean Franc'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
    ]
