# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_bulkenrollment_enrollment_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='adminrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='revoked_by',
        ),
        migrations.RemoveField(
            model_name='adminrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bulkenrollment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bulkenrollment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bulkenrollment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bulkenrollment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='order',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.DeleteModel(
            name='PaymentReference',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_is_corp_83b0a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_tra_enrollm_3a6b75_idx',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='enrollment_type',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='individual_email',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='individual_name',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='individual_phone',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='is_corporate',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='vat_number',
        ),
        migrations.AlterField(
            model_name='cart',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='countrypaymentlandscape',
            name='local_currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], max_length=5, verbose_name='Local Currency'),
        ),
        migrations.AlterField(
            model_name='depositrecord',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('XOF', 'West African CFA Franc'), ('SLL', 'Sierra Leonean Leone'), ('GMD', 'Gambian Dalasi'), ('LRD', 'Liberian Dollar'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling'), ('UGX', 'Ugandan Shilling'), ('RWF', 'Rwandan Franc'), ('ETB', 'Ethiopian Birr'), ('SOS', 'Somali Shilling'), ('BIF', 'Burundian Franc'), ('DJF', 'Djiboutian Franc'), ('ZAR', 'South African Rand'), ('ZMW', 'Zambian Kwacha'), ('ZWL', 'Zimbabwean Dollar'), ('MWK', 'Malawian Kwacha'), ('MZN', 'Mozambican Metical'), ('AOA', 'Angolan Kwanza'), ('SZL', 'Swazi Lilangeni'), ('LSL', 'Lesotho Loti'), ('NAD', 'Namibian Dollar'), ('BWP', 'Botswana Pula'), ('MGA', 'Malagasy Ariary'), ('SCR', 'Seychellois Rupee'), ('MUR', 'Mauritian Rupee'), ('EGP', 'Egyptian Pound'), ('MAD', 'Moroccan Dirham'), ('DZD', 'Algerian Dinar'), ('TND', 'Tunisian Dinar'), ('LYD', 'Libyan Dinar'), ('SDG', 'Sudanese Pound'), ('MRU', 'Mauritanian Ouguiya'), ('XAF', 'Central African CFA Franc'), ('CDF', 'Congolese Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('AED', 'UAE Dirham')], default='USD', max_length=5, verbose_name='Currency'),
        ),
        migrations.DeleteModel(
            name='AdminRole',
        ),
        migrations.DeleteModel(
            name='BulkEnrollment',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
