# Generated by Django 4.2.16 on 2026-02-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_adminrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='providercountryconfig',
            name='is_sandbox',
            field=models.BooleanField(default=True, verbose_name='Sandbox Mode'),
        ),
    ]
