# Generated by Django 4.2.16 on 2026-02-23 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_company_companylearner_and_more'),
        ('payments', '0010_alter_depositrecord_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider_method',
            field=models.CharField(blank=True, choices=[('card', 'Credit/Debit Card'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('ussd', 'USSD'), ('bank_redirect', 'Bank Redirect'), ('qr_code', 'QR Code'), ('cash', 'Cash Deposit'), ('wallet', 'Digital Wallet'), ('pos', 'Point of Sale'), ('agent', 'Agent Network'), ('cheque', 'Cheque'), ('eft', 'Electronic Funds Transfer')], max_length=20, null=True, verbose_name='Payment Method'),
        ),
    ]
