# Generated by Django 4.2.16 on 2026-02-23 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_company_companylearner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0011_alter_paymenttransaction_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_address',
            field=models.TextField(blank=True, null=True, verbose_name='Company Address'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Company Phone'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='enrollment_type',
            field=models.CharField(blank=True, choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry', 'Industry Training'), ('custom_selection', 'Custom Selection')], help_text='Type of enrollment this payment is for', max_length=20, null=True, verbose_name='Enrollment Type'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='individual_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Individual Email'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='individual_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Individual Name'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='individual_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Individual Phone'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='Whether this is a corporate/company payment', verbose_name='Corporate Payment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='vat_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VAT/Tax Number'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
    ]
