# Generated by Django for admin chat system integration
# This migration adds Django models for existing database tables created via SQL

from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('localization', '0001_initial'),
        ('communication', '0001_initial'),
        ('payments', '0020_simplify_pricing_remove_vat'),
    ]

    operations = [
        # Create Administrator model (maps to existing 'administrators' table)
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(help_text='Unique identifier like ADM-DB8E23C1', max_length=100, unique=True, verbose_name='Admin ID')),
                ('admin_type', models.CharField(choices=[('hr', 'HR Administrator'), ('executive', 'Executive Administrator'), ('sales', 'Sales Administrator'), ('marketing', 'Marketing Administrator'), ('payment', 'Payment Administrator'), ('system', 'System Administrator'), ('general', 'General Administrator')], default='general', max_length=50, verbose_name='Administrator Type')),
                ('is_executive_admin', models.BooleanField(default=False, help_text='Has executive admin privileges', verbose_name='Executive Admin')),
                ('is_sales_admin', models.BooleanField(default=False, help_text='Has sales admin privileges', verbose_name='Sales Admin')),
                ('is_marketing_admin', models.BooleanField(default=False, help_text='Has marketing admin privileges', verbose_name='Marketing Admin')),
                ('is_active', models.BooleanField(default=True, help_text='Is this administrator account active?', verbose_name='Active')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Additional role-specific permissions', verbose_name='Custom Permissions')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrator_profiles', to='users.user', verbose_name='User Account')),
            ],
            options={
                'db_table': 'administrators',
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
                'ordering': ['admin_type', 'admin_id'],
            },
        ),
        # Create ExecutiveCountryAssignment model (maps to existing 'executive_country_assignments' table)
        migrations.CreateModel(
            name='ExecutiveCountryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_level', models.CharField(choices=[('country', 'Country Level'), ('region', 'Regional Level'), ('subregion', 'Sub-Region Level'), ('province', 'Province/State Level')], default='country', max_length=50, verbose_name='Region Level')),
                ('assignment_type', models.CharField(choices=[('executive_coverage', 'Executive Coverage'), ('supervision', 'Supervision'), ('accountability', 'Accountability'), ('support', 'Support')], default='executive_coverage', max_length=50, verbose_name='Assignment Type')),
                ('assigned_at', models.DateTimeField(default=timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('coverage_area', models.TextField(blank=True, help_text='Specific geographic area coverage details', verbose_name='Coverage Area')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of responsibilities for this assignment', verbose_name='Responsibilities')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_executive_countries', to='users.user', verbose_name='Assigned By')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executive_admin_assignments', to='localization.country', verbose_name='Country')),
                ('executive_admin', models.ForeignKey(help_text='Executive admin assigned to this country', on_delete=django.db.models.deletion.CASCADE, related_name='executive_country_assignments', to='payments.administrator', verbose_name='Executive Administrator')),
            ],
            options={
                'db_table': 'executive_country_assignments',
                'verbose_name': 'Executive Country Assignment',
                'verbose_name_plural': 'Executive Country Assignments',
                'unique_together': {('executive_admin', 'country')},
                'ordering': ['country__name', 'executive_admin__admin_id'],
            },
        ),
        # Create SalesMarketingCountryAssignment model (maps to existing 'sales_marketing_country_assignments' table)
        migrations.CreateModel(
            name='SalesMarketingCountryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_type', models.CharField(choices=[('sales', 'Sales Admin'), ('marketing', 'Marketing Admin'), ('both', 'Sales & Marketing Admin')], default='sales', max_length=50, verbose_name='Admin Type')),
                ('assignment_type', models.CharField(choices=[('sales_coverage', 'Sales Coverage'), ('market_development', 'Market Development'), ('client_acquisition', 'Client Acquisition'), ('brand_promotion', 'Brand Promotion')], default='sales_coverage', max_length=50, verbose_name='Assignment Type')),
                ('assigned_at', models.DateTimeField(default=timezone.now)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sales_target', models.DecimalField(blank=True, decimal_places=2, help_text='Sales target amount for this country', max_digits=12, null=True, verbose_name='Sales Target')),
                ('marketing_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Marketing budget for this country', max_digits=12, null=True, verbose_name='Marketing Budget')),
                ('performance_metrics', models.JSONField(blank=True, default=dict, help_text='KPIs and performance metrics for this assignment', verbose_name='Performance Metrics')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sales_marketing_countries', to='users.user', verbose_name='Assigned By')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_marketing_assignments', to='localization.country', verbose_name='Country')),
                ('sales_marketing_admin', models.ForeignKey(help_text='Sales or marketing admin assigned to this country', on_delete=django.db.models.deletion.CASCADE, related_name='sales_marketing_country_assignments', to='payments.administrator', verbose_name='Sales/Marketing Administrator')),
            ],
            options={
                'db_table': 'sales_marketing_country_assignments',
                'verbose_name': 'Sales/Marketing Country Assignment',
                'verbose_name_plural': 'Sales/Marketing Country Assignments',
                'unique_together': {('sales_marketing_admin', 'country')},
                'ordering': ['country__name', 'sales_marketing_admin__admin_id'],
            },
        ),
        # Create AdminChatRelationship model (maps to existing 'admin_chat_relationships' table)
        migrations.CreateModel(
            name='AdminChatRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('country_linked', 'Country-Linked'), ('hierarchical', 'Hierarchical (HR→Executive)'), ('functional', 'Functional Collaboration'), ('operational', 'Operational Coordination'), ('emergency', 'Emergency Contact')], default='country_linked', max_length=50, verbose_name='Relationship Type')),
                ('can_chat_directly', models.BooleanField(default=True, help_text='Allow direct 1-on-1 chats between these admins', verbose_name='Can Chat Directly')),
                ('chat_permissions', models.JSONField(blank=True, default=dict, help_text='Specific permissions for this chat relationship', verbose_name='Chat Permissions')),
                ('last_chat_at', models.DateTimeField(blank=True, help_text='When was the last chat between these admins', null=True, verbose_name='Last Chat At')),
                ('chat_count', models.IntegerField(default=0, help_text='Number of chats between these admins', verbose_name='Chat Count')),
                ('is_active', models.BooleanField(default=True, help_text='Is this chat relationship active?', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_relationships_as_admin1', to='payments.administrator', verbose_name='Admin 1')),
                ('admin2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_relationships_as_admin2', to='payments.administrator', verbose_name='Admin 2')),
                ('chat_room', models.ForeignKey(blank=True, help_text='Socket.io chat room for this relationship', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_relationships', to='communication.chatroom', verbose_name='Chat Room')),
                ('country', models.ForeignKey(blank=True, help_text='Country linking these admins (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_chat_relationships', to='localization.country', verbose_name='Linked Country')),
            ],
            options={
                'db_table': 'admin_chat_relationships',
                'verbose_name': 'Admin Chat Relationship',
                'verbose_name_plural': 'Admin Chat Relationships',
                'unique_together': {('admin1', 'admin2', 'country')},
                'ordering': ['-last_chat_at', '-created_at'],
            },
        ),
        # Create SystemAdminChatAccess model (maps to existing 'system_admin_chat_access' table)
        migrations.CreateModel(
            name='SystemAdminChatAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_category', models.CharField(blank=True, choices=[('technical', 'Technical Issue'), ('billing', 'Billing/Payment Issue'), ('access', 'Access/Login Issue'), ('data', 'Data/Report Issue'), ('system', 'System Performance'), ('security', 'Security Concern'), ('feature', 'Feature Request'), ('complaint', 'Complaint'), ('other', 'Other')], max_length=100, verbose_name='Issue Category')),
                ('issue_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20, verbose_name='Issue Priority')),
                ('issue_description', models.TextField(blank=True, verbose_name='Issue Description')),
                ('last_report_at', models.DateTimeField(blank=True, help_text='When was the last issue reported', null=True, verbose_name='Last Report At')),
                ('report_count', models.IntegerField(default=0, verbose_name='Report Count')),
                ('resolution_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=50, verbose_name='Resolution Status')),
                ('is_active', models.BooleanField(default=True, help_text='Is this chat access channel active?', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(help_text='Admin who has system admin chat access', on_delete=django.db.models.deletion.CASCADE, related_name='system_admin_chat_accesses', to='payments.administrator', verbose_name='Administrator')),
                ('chat_room', models.ForeignKey(blank=True, help_text='Socket.io chat room for system admin support', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_admin_chat_accesses', to='communication.chatroom', verbose_name='Chat Room')),
                ('system_admin', models.ForeignKey(help_text='System admin available for support', on_delete=django.db.models.deletion.CASCADE, related_name='admin_chat_accesses', to='payments.administrator', verbose_name='System Administrator')),
            ],
            options={
                'db_table': 'system_admin_chat_access',
                'verbose_name': 'System Admin Chat Access',
                'verbose_name_plural': 'System Admin Chat Access',
                'unique_together': {('admin', 'system_admin')},
                'ordering': ['-last_report_at', 'admin__admin_id'],
            },
        ),
        # Create indexes for performance (mostly these should already exist from SQL, but Django will manage them)
        migrations.AddIndex(
            model_name='administrator',
            index=models.Index(fields=['admin_type', 'is_active'], name='idx_admin_type_active'),
        ),
        migrations.AddIndex(
            model_name='administrator',
            index=models.Index(fields=['admin_id'], name='idx_admin_id'),
        ),
        migrations.AddIndex(
            model_name='executivecountryassignment',
            index=models.Index(fields=['executive_admin', 'is_active'], name='idx_exec_country_admin_active'),
        ),
        migrations.AddIndex(
            model_name='executivecountryassignment',
            index=models.Index(fields=['country', 'is_active'], name='idx_exec_country_country_active'),
        ),
        migrations.AddIndex(
            model_name='salesmarketingcountryassignment',
            index=models.Index(fields=['sales_marketing_admin', 'is_active'], name='idx_sales_marketing_admin_active'),
        ),
        migrations.AddIndex(
            model_name='salesmarketingcountryassignment',
            index=models.Index(fields=['country', 'is_active'], name='idx_sales_marketing_country_active'),
        ),
        migrations.AddIndex(
            model_name='salesmarketingcountryassignment',
            index=models.Index(fields=['admin_type', 'is_active'], name='idx_sales_marketing_type_active'),
        ),
        migrations.AddIndex(
            model_name='adminchatrelationship',
            index=models.Index(fields=['admin1', 'admin2', 'is_active'], name='idx_admin_chat_admins_active'),
        ),
        migrations.AddIndex(
            model_name='adminchatrelationship',
            index=models.Index(fields=['country', 'is_active'], name='idx_admin_chat_country_active'),
        ),
        migrations.AddIndex(
            model_name='systemadminchataccess',
            index=models.Index(fields=['admin', 'is_active'], name='idx_system_chat_admin_active'),
        ),
        migrations.AddIndex(
            model_name='systemadminchataccess',
            index=models.Index(fields=['system_admin', 'is_active'], name='idx_system_chat_system_admin_active'),
        ),
        # Add many-to-many relationship for Administrator.assigned_countries
        migrations.AddField(
            model_name='administrator',
            name='assigned_countries',
            field=models.ManyToManyField(blank=True, related_name='executive_admins', through='payments.ExecutiveCountryAssignment', to='localization.country', verbose_name='Assigned Countries'),
        ),
    ]