# Generated by Django 4.2.16 on 2026-03-16 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_add_pathway_enrollment_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AfricanBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(help_text="Internal bank code (e.g., 'absa', 'kcb')", max_length=50)),
                ('swift_code', models.CharField(blank=True, help_text='SWIFT/BIC code', max_length=11)),
                ('bank_code', models.CharField(blank=True, help_text='Local bank/branch code', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommended', models.BooleanField(default=False, help_text='Show as recommended option')),
                ('priority', models.IntegerField(default=0, help_text='Sort order within country')),
                ('category', models.CharField(default='commercial_bank', help_text='Bank category (commercial_bank, payment_gateway, mobile_money, etc.)', max_length=50)),
                ('provider_type', models.CharField(default='bank', help_text='Type: bank or payment_provider', max_length=50)),
                ('api_integration_code', models.CharField(blank=True, help_text='API integration code for payment provider', max_length=50)),
                ('supports_card', models.BooleanField(default=False)),
                ('supports_mobile_money', models.BooleanField(default=False)),
                ('supports_eft', models.BooleanField(default=False)),
                ('supports_qr', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True, help_text='Logo URL for the bank/provider')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'African Bank',
                'verbose_name_plural': 'African Banks',
                'ordering': ['country', 'priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AfricanCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code', max_length=3)),
                ('currency_symbol', models.CharField(blank=True, max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Sort order for dropdown')),
            ],
            options={
                'verbose_name': 'African Country',
                'verbose_name_plural': 'African Countries',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BankAccountTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number_pattern', models.CharField(blank=True, help_text='Regex pattern for validation', max_length=100)),
                ('supports_savings', models.BooleanField(default=True)),
                ('supports_current', models.BooleanField(default=True)),
                ('supports_business', models.BooleanField(default=True)),
                ('min_transfer_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum transfer amount in local currency', max_digits=12, null=True)),
                ('max_transfer_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum transfer amount per transaction', max_digits=12, null=True)),
                ('max_daily_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum daily transfer limit', max_digits=12, null=True)),
                ('transfer_fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee per transfer', max_digits=10)),
                ('transfer_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage fee of transfer amount', max_digits=5)),
            ],
            options={
                'verbose_name': 'Bank Account Template',
                'verbose_name_plural': 'Bank Account Templates',
            },
        ),
        migrations.CreateModel(
            name='CompanyBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=11)),
                ('bank_code', models.CharField(blank=True, max_length=20)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(default='Current Account', max_length=50)),
                ('currency', models.CharField(help_text='Account currency (e.g., ZAR, USD)', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default account for this country')),
                ('priority', models.IntegerField(default=0, help_text='Sort order')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Bank Account',
                'verbose_name_plural': 'Company Bank Accounts',
                'ordering': ['country', 'priority', 'bank_name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='adminchatrelationship',
            name='idx_admin_chat_admins_active',
        ),
        migrations.RemoveIndex(
            model_name='adminchatrelationship',
            name='idx_admin_chat_country_active',
        ),
        migrations.RemoveIndex(
            model_name='administrator',
            name='idx_admin_type_active',
        ),
        migrations.RemoveIndex(
            model_name='administrator',
            name='idx_admin_id',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_status_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_user_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='enrollment',
            name='enrollments_type_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='executivecountryassignment',
            name='idx_exec_country_admin_active',
        ),
        migrations.RemoveIndex(
            model_name='executivecountryassignment',
            name='idx_exec_country_country_active',
        ),
        migrations.RemoveIndex(
            model_name='salesmarketingcountryassignment',
            name='idx_sales_marketing_admin_active',
        ),
        migrations.RemoveIndex(
            model_name='salesmarketingcountryassignment',
            name='idx_sales_marketing_country_active',
        ),
        migrations.RemoveIndex(
            model_name='salesmarketingcountryassignment',
            name='idx_sales_marketing_type_active',
        ),
        migrations.RemoveIndex(
            model_name='systemadminchataccess',
            name='idx_system_chat_admin_active',
        ),
        migrations.RemoveIndex(
            model_name='systemadminchataccess',
            name='idx_system_chat_system_admin_active',
        ),
        migrations.RenameIndex(
            model_name='admincountryaccess',
            new_name='admin_count_admin_r_71660c_idx',
            old_name='admin_count_admin_r_rol_5f8d9a_idx',
        ),
        migrations.RenameIndex(
            model_name='admincountryaccess',
            new_name='admin_count_country_2f1eda_idx',
            old_name='admin_count_country_rol_2c4e5b_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_learner_401c60_idx',
            old_name='payments_en_learners_e9d2b8_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_masterc_6e01ac_idx',
            old_name='payments_en_masterc_7c4d91_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_aicerts_65c536_idx',
            old_name='payments_en_aicerts_e4f5c2_idx',
        ),
        migrations.RenameIndex(
            model_name='enrollment',
            new_name='enrollments_industr_8e4a84_idx',
            old_name='payments_en_industr_2a3f1a_idx',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='allergies',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='bank_account_holder_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='bank_account_type',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='bank_branch_code',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='certification_declaration_accepted',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='company_vat_number',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='confirmed_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='data_protection_accepted',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='disability',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='dropped_out_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='existing_skills',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='funding_source',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='has_cv',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='has_id_copy',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='has_motivational_letter',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='has_previous_learnership_experience',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='has_proof_of_residence',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='has_qualification_certificates',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='highest_qualification',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='learning_support_details',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='medical_conditions',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='medications',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='monthly_income',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='next_of_kin_address',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='next_of_kin_email',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='next_of_kin_phone',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='next_of_kin_relationship',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='prerequisites_verified',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='previous_learnership_details',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='purchase_order_number',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='qualification_institution',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='qualification_year',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='race',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='referral_source',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='requires_debit_order',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='requires_learning_support',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='seta_declaration_accepted',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='verified_at',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_amount',
            field=models.DecimalField(blank=True, db_column='final_amount', decimal_places=2, default=0, help_text='Exact course price - no VAT, no additional fees', max_digits=12, null=True, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instructor_id',
            field=models.BigIntegerField(blank=True, help_text='Instructor teaching this course', null=True, verbose_name='Instructor ID'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student_id',
            field=models.BigIntegerField(blank=True, help_text='Unique student identifier across all enrollment pathways', null=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='notes',
            field=models.TextField(blank=True, help_text='Administrative notes about this admin', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='accessibility_needs',
            field=models.TextField(blank=True, help_text='Any accessibility requirements', null=True, verbose_name='Accessibility Needs'),
        ),
        migrations.AlterField(
            model_name='systemadminchataccess',
            name='issue_category',
            field=models.CharField(blank=True, choices=[('technical', 'Technical Issue'), ('billing', 'Billing/Payment Issue'), ('access', 'Access/Login Issue'), ('data', 'Data/Report Issue'), ('system', 'System Performance'), ('security', 'Security Concern'), ('feature', 'Feature Request'), ('complaint', 'Complaint'), ('other', 'Other')], help_text='General category of issues discussed', max_length=100, verbose_name='Issue Category'),
        ),
        migrations.AlterField(
            model_name='systemadminchataccess',
            name='issue_description',
            field=models.TextField(blank=True, help_text='General description of typical issues', verbose_name='Issue Description'),
        ),
        migrations.AlterField(
            model_name='systemadminchataccess',
            name='issue_priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', help_text='Priority level for issues', max_length=20, verbose_name='Issue Priority'),
        ),
        migrations.AlterField(
            model_name='systemadminchataccess',
            name='report_count',
            field=models.IntegerField(default=0, help_text='Number of issues reported through this channel', verbose_name='Report Count'),
        ),
        migrations.AlterField(
            model_name='systemadminchataccess',
            name='resolution_status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', help_text='Current status of reported issues', max_length=50, verbose_name='Resolution Status'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student_id'], name='enrollments_student_379f04_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['instructor_id'], name='enrollments_instruc_74bcc2_idx'),
        ),
        migrations.AddField(
            model_name='companybankaccount',
            name='country',
            field=models.ForeignKey(help_text='Country where account is held', on_delete=django.db.models.deletion.CASCADE, related_name='company_accounts', to='payments.africancountry'),
        ),
        migrations.AddField(
            model_name='bankaccounttemplate',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_templates', to='payments.africanbank', verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='africanbank',
            name='country',
            field=models.ForeignKey(help_text='Country where bank operates', on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='payments.africancountry'),
        ),
        migrations.AddField(
            model_name='africanbank',
            name='payment_providers',
            field=models.ManyToManyField(blank=True, help_text='Payment providers that can process transfers from this bank', related_name='banks', to='payments.paymentprovidermodel'),
        ),
        migrations.AddIndex(
            model_name='companybankaccount',
            index=models.Index(fields=['country', 'is_active'], name='payments_co_country_a5d66e_idx'),
        ),
        migrations.AddIndex(
            model_name='companybankaccount',
            index=models.Index(fields=['country', 'is_default'], name='payments_co_country_ead5fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companybankaccount',
            unique_together={('country', 'bank_name', 'account_number')},
        ),
        migrations.AddIndex(
            model_name='africanbank',
            index=models.Index(fields=['country', 'is_active'], name='payments_af_country_d179ea_idx'),
        ),
        migrations.AddIndex(
            model_name='africanbank',
            index=models.Index(fields=['country', 'is_recommended'], name='payments_af_country_cfe624_idx'),
        ),
        migrations.AddIndex(
            model_name='africanbank',
            index=models.Index(fields=['swift_code'], name='payments_af_swift_c_69c1df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='africanbank',
            unique_together={('country', 'code')},
        ),
    ]
