# Generated by Django 4.2.16 on 2026-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_africanbank_africancountry_bankaccounttemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(default='ZA', max_length=2)),
                ('verified', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment OTP Verification',
                'verbose_name_plural': 'Payment OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'verified'], name='payments_pa_email_522ac6_idx'), models.Index(fields=['payment_token'], name='payments_pa_payment_e0364b_idx'), models.Index(fields=['expires_at'], name='payments_pa_expires_04a29a_idx')],
            },
        ),
    ]
