# Generated by Django 4.2.16 on 2026-04-15 15:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0012_add_smatpay_fee_fields'),
        ('payments', '0032_remove_paymentotpverification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactverificationotp',
            new_name='payments_co_contact_03aa7b_idx',
            old_name='payments_co_contact_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='smatpay_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SmatPay fee calculated for LMS accounting', max_digits=10, verbose_name='SmatPay Fee Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='smatpay_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='SmatPay fee percentage applied', max_digits=5, verbose_name='SmatPay Fee Percentage'),
        ),
        migrations.AlterField(
            model_name='adminrole',
            name='role_type',
            field=models.CharField(choices=[('payment_admin', 'Payment Admin'), ('payment_sales_marketing_admin', 'Payment, Sales & Marketing Admin'), ('hr_admin', 'HR Admin'), ('executive_admin', 'Executive Admin')], max_length=50, verbose_name='Role Type'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='background_color',
            field=models.CharField(default='#172E3D', help_text='Banner background color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Countries where this promotion is displayed. Empty = all countries.', related_name='coupon_promotions', to='localization.country'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='country_restriction',
            field=models.CharField(blank=True, help_text='ISO-2 code for single-country coupon validation. Leave blank for all.', max_length=2),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='cta_text',
            field=models.CharField(default='Enroll Now', help_text='Call-to-action button text on promo flyer', max_length=100),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='cta_url',
            field=models.URLField(blank=True, help_text='Link when user taps the flyer CTA'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, help_text='Percentage (0–100) or fixed USD amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji or icon for promotion (e.g. 🎉, 💰, 🎓)', max_length=50),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='image_url',
            field=models.URLField(blank=True, help_text='Optional banner image URL'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Max cap in USD for capped_percentage type', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='min_purchase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount in USD to apply this coupon', max_digits=10),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='per_user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Max redemptions per email address'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher = shown first (0–100)'),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='product_pathway',
            field=models.CharField(choices=[('all', 'All Products'), ('masterclass', 'Masterclasses'), ('learnership', 'Learnerships'), ('industry_training', 'Industry-Based Training'), ('aicerts', 'AICERTS Courses'), ('custom', 'Custom Selection'), ('aicerts_custom_industry', 'AICERTS + Custom + Industry Training')], default='all', max_length=30),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='text_color',
            field=models.CharField(default='#FFFFFF', help_text='Text color (hex code)', max_length=7),
        ),
        migrations.AlterField(
            model_name='couponcode',
            name='usage_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Max total redemptions. Leave blank for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='aicerts_enrollment_id',
            field=models.IntegerField(blank=True, default=None, help_text='FK to aicerts_enrollments.id', null=True, verbose_name='AICerts Enrollment ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Enrollment Data'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='final_amount',
            field=models.DecimalField(blank=True, db_column='final_amount', decimal_places=2, default=0, max_digits=12, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='industry_enrollment_id',
            field=models.IntegerField(blank=True, default=None, help_text='FK to industry_based_training_industrytrainingenrollment.id', null=True, verbose_name='Industry Enrollment ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_address',
            field=models.TextField(blank=True, db_column='student_address', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_city',
            field=models.CharField(blank=True, db_column='student_city', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_country',
            field=models.CharField(db_column='student_country', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_dob',
            field=models.DateField(blank=True, db_column='student_dob', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_email',
            field=models.EmailField(db_column='student_email', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_full_name',
            field=models.CharField(db_column='student_full_name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_gender',
            field=models.CharField(blank=True, db_column='student_gender', max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_id_number',
            field=models.CharField(blank=True, db_column='student_id_number', max_length=50, null=True, verbose_name='ID/Passport Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_phone',
            field=models.CharField(db_column='student_phone', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_postal_code',
            field=models.CharField(blank=True, db_column='student_postal_code', max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learnership_enrollment_id',
            field=models.IntegerField(blank=True, default=None, help_text='FK to learnerships_learnershipenrollment.id', null=True, verbose_name='Learnership Enrollment ID'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='masterclass_enrollment_id',
            field=models.IntegerField(blank=True, default=None, help_text='FK to masterclasses_masterclassenrollment.id', null=True, verbose_name='Masterclass Enrollment ID'),
        ),
    ]
