# Generated by Django 4.2.16 on 2026-04-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0034_quotation_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('country', models.CharField(default='ZA', max_length=2)),
                ('verified', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('payment_token', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment OTP Verification',
                'verbose_name_plural': 'Payment OTP Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='quotationactivitylog',
            name='performed_by',
        ),
        migrations.RemoveField(
            model_name='quotationactivitylog',
            name='quotation',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='quotation',
        ),
        migrations.DeleteModel(
            name='QuotationTemplate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='smatpay_fee_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='smatpay_fee_percentage',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_country',
            field=models.CharField(max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_full_name',
            field=models.CharField(max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID/Passport Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
        migrations.DeleteModel(
            name='ClientQuotation',
        ),
        migrations.DeleteModel(
            name='QuotationActivityLog',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.AddIndex(
            model_name='paymentotpverification',
            index=models.Index(fields=['email', 'verified'], name='payments_pa_email_522ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentotpverification',
            index=models.Index(fields=['payment_token'], name='payments_pa_payment_e0364b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentotpverification',
            index=models.Index(fields=['expires_at'], name='payments_pa_expires_04a29a_idx'),
        ),
    ]
