# Generated by Django 4.2.16 on 2026-04-24 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0036_clientquotation_quotationtemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_mailing_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mailing List',
                'verbose_name_plural': 'Mailing Lists',
                'db_table': 'marketing_mailing_lists',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MailingListContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(default='+27', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailing_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='payments.mailinglist')),
            ],
            options={
                'verbose_name': 'Mailing List Contact',
                'verbose_name_plural': 'Mailing List Contacts',
                'db_table': 'marketing_mailing_list_contacts',
                'ordering': ['name'],
            },
        ),
    ]
