# Generated by Django 4.2.16 on 2026-04-24 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0038_mailinglist_enhancements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglist',
            name='country',
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='is_universal',
        ),
        migrations.RemoveField(
            model_name='mailinglist',
            name='theme',
        ),
    ]
