# Generated by Django 4.2.16 on 2026-04-24 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0039_marketingcampaign'),
        ('payments', '0039_remove_mailinglist_country_and_more'),
    ]

    operations = [
    ]
