# Generated by Django 4.2.16 on 2026-04-24 23:09

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0012_add_smatpay_fee_fields'),
        ('payments', '0040_merge_20260425_0107'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='clientquotation',
            name='client_quot_quotati_c7c7df_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientquotation',
            name='client_quot_client__21bc6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientquotation',
            name='client_quot_status_b10802_idx',
        ),
        migrations.RemoveIndex(
            model_name='clientquotation',
            name='client_quot_trainin_989a5d_idx',
        ),
        migrations.RenameField(
            model_name='quotationitem',
            old_name='unit_price',
            new_name='unit_price_usd',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='learnership_id',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='learnership_name',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='local_amount',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='masterclass_id',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='masterclass_name',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='training_type',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='vat_amount',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='total_price',
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='discount_amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount Amount (USD)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='introduction',
            field=models.TextField(blank=True, help_text='Paragraph explaining the product/service', verbose_name='Introduction'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='is_universal',
            field=models.BooleanField(default=False, verbose_name='Is Universal (USD Only)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Bullet-separated list of prerequisites', verbose_name='Prerequisites'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='subtotal_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal (USD)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='tax_amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Tax Amount (USD)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='total_amount_local',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Amount (Local)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='total_amount_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total Amount (USD)'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='country',
            field=models.CharField(blank=True, help_text='Specific country for this list', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='is_universal',
            field=models.BooleanField(default=False, help_text='True if this list is for all countries'),
        ),
        migrations.AddField(
            model_name='mailinglist',
            name='theme',
            field=models.CharField(blank=True, help_text='Category or theme for this list', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Item Code'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Item ID'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Price (USD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='training_type',
            field=models.CharField(choices=[('course', 'AICERTS Course'), ('masterclass', 'Professional Masterclass'), ('learnership', 'Learnership Program'), ('industry_training', 'Industry-Based Training')], default=0, max_length=20, verbose_name='Training Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='client_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='localization.country', verbose_name='Target Country'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=10, verbose_name='Exchange Rate (USD to Local)'),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='training_type',
            field=models.CharField(choices=[('course', 'AICERTS Course'), ('masterclass', 'Professional Masterclass'), ('learnership', 'Learnership Program'), ('industry_training', 'Industry-Based Training')], max_length=20, verbose_name='Training Type'),
        ),
    ]
