# Generated by Django 4.2.16 on 2026-04-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0041_remove_clientquotation_client_quot_quotati_c7c7df_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientquotation',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of additional recipients [{name, email, phone}]', verbose_name='Bulk Recipients'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='stream',
            field=models.CharField(blank=True, help_text='AI & Blockchain or Cybersecurity', max_length=50, verbose_name='Training Stream'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='client_email',
            field=models.EmailField(help_text='Primary contact email', max_length=254, verbose_name='Client Email'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='client_name',
            field=models.CharField(help_text='Primary contact name', max_length=255, verbose_name='Client Name'),
        ),
    ]
