# Generated by Django 4.2.16 on 2026-04-25 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0042_clientquotation_recipients_quotationitem_stream_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='contactverificationotp',
            new_name='payments_co_contact_03aa7b_idx',
            old_name='payments_co_contact_idx',
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='quotation_type',
            field=models.CharField(choices=[('corporate', 'Corporate/Organization'), ('individual', 'Individual Clients')], default='corporate', max_length=20, verbose_name='Quotation Type'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='recipients',
            field=models.JSONField(blank=True, default=list, help_text='List of additional recipients [{name, email, phone, country_code}]', verbose_name='Bulk Recipients'),
        ),
    ]
