# Generated by Django 4.2.16 on 2026-04-26 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0043_rename_payments_co_contact_idx_payments_co_contact_03aa7b_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrole',
            name='role_type',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('payment_admin', 'Payment Operations Admin'), ('marketing_admin', 'Sales & Marketing Admin'), ('payment_sales_marketing_admin', 'Unified Payment & Marketing Admin'), ('hr_admin', 'HR Admin'), ('executive_admin', 'Executive Admin')], max_length=50, verbose_name='Role Type'),
        ),
    ]
