# Generated by Django 4.2.16 on 2026-04-26 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0012_add_smatpay_fee_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0044_alter_adminrole_role_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRoleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=191, verbose_name='Candidate Full Name')),
                ('candidate_email', models.EmailField(max_length=254, verbose_name='Candidate Email')),
                ('proposed_role', models.CharField(choices=[('system_admin', 'System Administrator'), ('payment_admin', 'Payment Administrator'), ('marketing_admin', 'Marketing Administrator'), ('hr_admin', 'HR Administrator'), ('executive_admin', 'Executive Administrator')], max_length=50, verbose_name='Proposed Role')),
                ('justification', models.TextField(blank=True, verbose_name='Justification/Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_role_requests', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_role_requests', to=settings.AUTH_USER_MODEL, verbose_name='Requested By')),
                ('target_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.country', verbose_name='Target Country')),
            ],
            options={
                'verbose_name': 'Admin Role Request',
                'verbose_name_plural': 'Admin Role Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
