# Generated by Django 4.2.16 on 2026-04-26 19:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0045_adminrolerequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotationitem',
            old_name='unit_price_usd',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='client_address',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='client_reference_code',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='discount_amount_usd',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='is_universal',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='quotation_type',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='recipients',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='subtotal_usd',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='tax_amount_usd',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='total_amount_local',
        ),
        migrations.RemoveField(
            model_name='clientquotation',
            name='total_amount_usd',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_code',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='total_price_usd',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='training_type',
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Base Price (USD)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='course_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Course ID (if type=course)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='course_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Course Name'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Discount Amount'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='learnership_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Learnership ID (if type=learnership)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='learnership_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Learnership Name'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='local_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount in Local Currency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='masterclass_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Masterclass ID (if type=masterclass)'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='masterclass_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Masterclass Name'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Number of Participants'),
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='training_type',
            field=models.CharField(choices=[('course', 'AI Certs Course'), ('masterclass', 'Professional Masterclass'), ('learnership', 'Learnership Program')], default='', max_length=20, verbose_name='Training Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientquotation',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='VAT/Tax Amount'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adminrolerequest',
            name='proposed_role',
            field=models.CharField(choices=[('system_admin', 'System Administrator'), ('payment_admin', 'Payment Operations Admin'), ('marketing_admin', 'Sales & Marketing Admin'), ('hr_admin', 'HR Administrator'), ('executive_admin', 'Executive Administrator')], max_length=50, verbose_name='Proposed Role'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='client_country',
            field=models.CharField(default='ZW', max_length=2, verbose_name='Country Code'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='client_email',
            field=models.EmailField(max_length=254, verbose_name='Client Email'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='client_name',
            field=models.CharField(max_length=255, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='clientquotation',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.0'), max_digits=10, verbose_name='Exchange Rate'),
        ),
        migrations.AlterField(
            model_name='quotationtemplate',
            name='training_type',
            field=models.CharField(choices=[('course', 'AI Certs Course'), ('masterclass', 'Professional Masterclass'), ('learnership', 'Learnership Program')], max_length=20, verbose_name='Training Type'),
        ),
        migrations.AddIndex(
            model_name='clientquotation',
            index=models.Index(fields=['quotation_number'], name='client_quot_quotati_c7c7df_idx'),
        ),
        migrations.AddIndex(
            model_name='clientquotation',
            index=models.Index(fields=['client_email'], name='client_quot_client__21bc6d_idx'),
        ),
        migrations.AddIndex(
            model_name='clientquotation',
            index=models.Index(fields=['status', 'created_at'], name='client_quot_status_b10802_idx'),
        ),
        migrations.AddIndex(
            model_name='clientquotation',
            index=models.Index(fields=['training_type', 'status'], name='client_quot_trainin_989a5d_idx'),
        ),
        migrations.AlterModelTable(
            name='adminrolerequest',
            table='payments_adminrolerequest',
        ),
    ]
