# Generated by Django 4.2.16 on 2026-04-27 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0046_rename_unit_price_usd_quotationitem_unit_price_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.DeleteModel(
            name='ExchangeRateLog',
        ),
    ]
