# Generated by Django 4.2.16 on 2026-05-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0048_enrollment_create_missing_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='enrollment_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='discount_applied',
        ),
        migrations.AddField(
            model_name='order',
            name='smatpay_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SmatPay fee calculated for LMS accounting', max_digits=10, verbose_name='SmatPay Fee Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='smatpay_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='SmatPay fee percentage applied', max_digits=5, verbose_name='SmatPay Fee Percentage'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_address',
            field=models.TextField(blank=True, db_column='student_address', null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_city',
            field=models.CharField(blank=True, db_column='student_city', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_country',
            field=models.CharField(db_column='student_country', max_length=100, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_dob',
            field=models.DateField(blank=True, db_column='student_dob', null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_email',
            field=models.EmailField(db_column='student_email', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_full_name',
            field=models.CharField(db_column='student_full_name', max_length=255, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_gender',
            field=models.CharField(blank=True, db_column='student_gender', max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_id_number',
            field=models.CharField(blank=True, db_column='student_id_number', max_length=50, null=True, verbose_name='ID/Passport Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_phone',
            field=models.CharField(db_column='student_phone', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learner_postal_code',
            field=models.CharField(blank=True, db_column='student_postal_code', max_length=20, null=True, verbose_name='Postal Code'),
        ),
    ]
