import re

with open("backend/apps/communication/services.py", "r") as f:
    content = f.read()

# In _ensure_course_room, we need to send a welcome message to the room if created,
# and notify the instructor that a new student joined. 
# We don't have instructor in _ensure_course_room, but we have item. We can find instructor.

# Wait, _ensure_instructor_direct_chat already finds the instructor. We could move the notification there.
# Let's patch _ensure_instructor_direct_chat first to notify the instructor

chat_instructor_patch = """
        # Send a welcome message from the instructor if it's the first time
        if created:
            Message.objects.create(
                sender=instructor,
                receiver=user,
                chat_room=room,
                message=f"Hello {user.first_name or user.username}, welcome to Hosi Academy! I am your instructor for this course. Feel free to reach out here if you have any questions.",
                message_type='text'
            )

        # Autogenerated message to instructor about student joining
        Message.objects.create(
            sender=user,
            receiver=instructor,
            chat_room=room,
            message=f"System Notification: Student {user.first_name or user.username} {user.last_name or ''} has joined your course.",
            message_type='text'
        )
"""

content = re.sub(
    r"# Send a welcome message from the instructor if it's the first time.*?(?=    @classmethod|$)",
    chat_instructor_patch,
    content,
    flags=re.DOTALL
)

# In _ensure_course_room, if created, send a message to the course room.
# It requires an instructor, which we might not have.
# Let's just create an autogenerated message from a system user or just the first instructor.

course_room_patch = """        room, created = ChatRoom.objects.get_or_create(
            id=room_id,
            defaults={
                'name': f"CHART: {room_name}",
                'description': f"Official discussion room for {room_name}",
                'chat_type': 'course',
                'course_app': app_label,
                'course_model': model_name,
                'course_id': item_id,
                'course_title': room_name
            }
        )
        ChatParticipant.objects.get_or_create(
            chat_room=room,
            user=user,
            defaults={'role': 'learner'}
        )
        
        # Determine instructor name for the welcome message
        instructor_name = "your Instructor"
        if hasattr(item, 'instructor') and item.instructor:
            instructor_name = getattr(item.instructor, 'first_name', '') + ' ' + getattr(item.instructor, 'last_name', '')
            if not instructor_name.strip():
                instructor_name = item.instructor.username
        
        # Welcome message to the course chat room
        if created:
            try:
                from apps.users.models import User
                system_user = User.objects.filter(is_superuser=True).first() or user
                Message.objects.create(
                    sender=system_user,
                    chat_room=room,
                    message=f"Welcome to the {room_name} Chat Group! {instructor_name} will be guiding you. Say hello to your classmates!",
                    message_type='text'
                )
            except Exception as e:
                logger.error(f"Failed to generate course welcome message: {e}")
"""

content = re.sub(
    r"        room, created = ChatRoom\.objects\.get_or_create\([\s\S]*?defaults=\{'role': 'learner'\}\n        \)",
    course_room_patch,
    content,
    flags=re.DOTALL
)

with open("backend/apps/communication/services.py", "w") as f:
    f.write(content)

print("Patched ChatEnforcerService")
