# Generated by Django 4.2.16 on 2026-02-03 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localization', '0005_state_city'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('payments', '0005_paymenttransaction_company_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text="Is this the user's current active cart?", verbose_name='Active')),
                ('status', models.CharField(choices=[('active', 'Active'), ('checkout', 'In Checkout'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20, verbose_name='Cart Status')),
                ('use_previous_company_details', models.BooleanField(default=False, help_text='Reuse company details from previous enrollment?', verbose_name='Reuse Previous Company Details')),
                ('is_corporate_enrollment', models.BooleanField(default=False, help_text='Is this a company-paid enrollment?', verbose_name='Corporate Enrollment')),
                ('total_courses', models.IntegerField(default=0, verbose_name='Total Courses')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Amount')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('checkout_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Checkout Started')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('abandoned_at', models.DateTimeField(blank=True, null=True, verbose_name='Abandoned At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_carts', to='payments.order', verbose_name='Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_carts', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Course Cart',
                'verbose_name_plural': 'Course Carts',
                'db_table': 'course_carts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., AICERTS, Udemy, Coursera', max_length=100, unique=True, verbose_name='Provider Name')),
                ('code', models.CharField(help_text='Unique identifier (e.g., aicerts, udemy)', max_length=50, unique=True, verbose_name='Provider Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website URL')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='providers/', verbose_name='Provider Logo')),
                ('api_url', models.URLField(blank=True, help_text='Base URL for provider API', verbose_name='API URL')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API Key')),
                ('is_active', models.BooleanField(default=True, help_text='Only active providers appear in custom enrollment catalog', verbose_name='Active')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Provider',
                'verbose_name_plural': 'Course Providers',
                'db_table': 'course_providers',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Course ID')),
                ('training_type', models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry Training'), ('custom_selection', 'Custom Selection')], max_length=20, verbose_name='Training Type')),
                ('interest_level', models.CharField(choices=[('high', 'High - Want to enroll soon'), ('medium', 'Medium - Considering'), ('low', 'Low - Just browsing')], default='medium', max_length=10, verbose_name='Interest Level')),
                ('intended_start', models.CharField(choices=[('immediate', 'Immediate (within 1 month)'), ('short_term', 'Short term (1-3 months)'), ('medium_term', 'Medium term (3-6 months)'), ('long_term', 'Long term (6+ months)'), ('undecided', 'Undecided')], default='undecided', max_length=20, verbose_name='Intended Start Time')),
                ('marketing_contacted', models.BooleanField(default=False, help_text='Has marketing team followed up on this lead?', verbose_name='Marketing Contacted')),
                ('marketing_contacted_at', models.DateTimeField(blank=True, null=True, verbose_name='Marketing Contact Date')),
                ('marketing_notes', models.TextField(blank=True, help_text='Notes from marketing follow-up', verbose_name='Marketing Notes')),
                ('converted_to_cart', models.BooleanField(default=False, help_text='Did learner add this to their cart?', verbose_name='Moved to Cart')),
                ('converted_to_cart_at', models.DateTimeField(blank=True, null=True, verbose_name='Added to Cart At')),
                ('converted_to_enrollment', models.BooleanField(default=False, help_text='Did learner complete enrollment?', verbose_name='Enrolled')),
                ('converted_to_enrollment_at', models.DateTimeField(blank=True, null=True, verbose_name='Enrolled At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added to Wishlist')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_wishlist_leads', to=settings.AUTH_USER_MODEL, verbose_name='Contacted By')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('masterclass', 'learnershipprogramme', 'aicertscourse', 'offering', 'course')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Course Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Wishlist Item',
                'verbose_name_plural': 'Wishlist',
                'db_table': 'wishlist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_used_company_name', models.CharField(blank=True, max_length=255, verbose_name='Last Used Company Name')),
                ('last_used_company_email', models.EmailField(blank=True, max_length=254, verbose_name='Last Used Company Email')),
                ('last_used_company_phone', models.CharField(blank=True, max_length=50, verbose_name='Last Used Company Phone')),
                ('last_used_company_address', models.TextField(blank=True, verbose_name='Last Used Company Address')),
                ('last_used_vat_number', models.CharField(blank=True, max_length=50, verbose_name='Last Used VAT Number')),
                ('has_company_payment_history', models.BooleanField(default=False, help_text='True if learner has paid via company before', verbose_name='Has Used Company Payment Before')),
                ('preferred_payment_provider', models.CharField(blank=True, help_text='Last used payment provider (paystack, flutterwave, etc.)', max_length=50, verbose_name='Preferred Payment Provider')),
                ('preferred_payment_method', models.CharField(blank=True, help_text='Last used payment method (card, mobile_money, bank_transfer)', max_length=20, verbose_name='Preferred Payment Method')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='Total Enrollments')),
                ('active_enrollments', models.IntegerField(default=0, verbose_name='Active Enrollments')),
                ('completed_enrollments', models.IntegerField(default=0, verbose_name='Completed Enrollments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferred_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_learners', to='localization.city', verbose_name='Preferred City')),
                ('preferred_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_learners', to='localization.country', verbose_name='Preferred Country')),
                ('preferred_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_learners', to='localization.state', verbose_name='Preferred State/Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learner_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Learner Profile',
                'verbose_name_plural': 'Learner Profiles',
                'db_table': 'learner_profiles',
            },
        ),
        migrations.CreateModel(
            name='CourseCatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Course ID')),
                ('training_type', models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry Training'), ('custom_selection', 'Custom Selection')], max_length=20, verbose_name='Training Type')),
                ('title', models.CharField(max_length=500, verbose_name='Course Title')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('thumbnail', models.URLField(blank=True, verbose_name='Thumbnail URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Show in catalog?', verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured course?', verbose_name='Featured')),
                ('total_enrollments', models.IntegerField(default=0, verbose_name='Total Enrollments')),
                ('total_wishlist_adds', models.IntegerField(default=0, verbose_name='Total Wishlist Adds')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('masterclass', 'learnershipprogramme', 'aicertscourse', 'offering', 'course')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Course Type')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_items', to='learner_portal.courseprovider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'Catalog Item',
                'verbose_name_plural': 'Course Catalog',
                'db_table': 'course_catalog',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Course ID')),
                ('training_type', models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry Training'), ('custom_selection', 'Custom Selection')], max_length=20, verbose_name='Training Type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('prerequisites_met', models.BooleanField(default=True, help_text='Does learner meet prerequisites for this course?', verbose_name='Prerequisites Met')),
                ('prerequisite_notes', models.TextField(blank=True, help_text='Details about prerequisites', verbose_name='Prerequisite Notes')),
                ('added_from_wishlist', models.BooleanField(default=False, verbose_name='Added from Wishlist')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Added to Cart')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='learner_portal.coursecart', verbose_name='Cart')),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('masterclass', 'learnershipprogramme', 'aicertscourse', 'offering', 'course')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Course Type')),
                ('wishlist_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='learner_portal.wishlist', verbose_name='Source Wishlist Item')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'db_table': 'course_cart_items',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user', 'training_type'], name='wishlist_user_id_fede94_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['marketing_contacted', 'interest_level'], name='wishlist_marketi_d52857_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['converted_to_cart', 'converted_to_enrollment'], name='wishlist_convert_713520_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['intended_start'], name='wishlist_intende_660f63_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='coursecatalogitem',
            index=models.Index(fields=['training_type', 'is_active'], name='course_cata_trainin_721aab_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecatalogitem',
            index=models.Index(fields=['provider', 'is_active'], name='course_cata_provide_ae61e4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecatalogitem',
            index=models.Index(fields=['-is_featured', '-total_enrollments'], name='course_cata_is_feat_a6f15b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='coursecatalogitem',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AlterUniqueTogether(
            name='coursecartitem',
            unique_together={('cart', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='coursecart',
            index=models.Index(fields=['user', 'is_active'], name='course_cart_user_id_3ef255_idx'),
        ),
        migrations.AddIndex(
            model_name='coursecart',
            index=models.Index(fields=['status', 'updated_at'], name='course_cart_status_e6639e_idx'),
        ),
    ]
