# Generated by Django 4.2.16 on 2026-02-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_portal', '0002_rename_learner_to_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='has_company_payment_history',
            field=models.BooleanField(default=False, help_text='True if student has paid via company before', verbose_name='Has Used Company Payment Before'),
        ),
    ]
