# Generated by Django 4.2.16 on 2026-02-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_portal', '0003_alter_studentprofile_has_company_payment_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='notes',
            field=models.TextField(blank=True, help_text='Why does the student want this course?', verbose_name='Reason for Interest'),
        ),
    ]
