# Generated by Django 4.2.16 on 2026-03-03 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learner_portal', '0005_coursecatalogitem_display_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecatalogitem',
            name='display_order',
        ),
    ]
