# Generated by Django 4.2.16 on 2026-03-16 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_company_companylearner_and_more'),
        ('localization', '0009_alter_city_options_state_alter_city_unique_together_and_more'),
        ('instructors', '0010_instructor_instructoractivitylog_instructorrating_and_more'),
        ('learner_portal', '0006_remove_coursecatalogitem_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Current city of residence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='localization.city', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Current country of residence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='localization.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='disability',
            field=models.CharField(blank=True, choices=[('none', 'No Disability'), ('physical', 'Physical Disability'), ('visual', 'Visual Impairment'), ('hearing', 'Hearing Impairment'), ('cognitive', 'Cognitive Disability'), ('other', 'Other')], max_length=10, null=True, verbose_name='Disability Status'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='employer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employer'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('self_employed', 'Self-Employed'), ('unemployed', 'Unemployed'), ('student', 'Student'), ('retired', 'Retired')], max_length=50, null=True, verbose_name='Employment Status'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, help_text='Date when student first enrolled', null=True, verbose_name='Enrollment Date'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Highest Qualification'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Primary instructor assigned to this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='instructors.instructor', verbose_name='Instructor'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job Title'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='provider',
            field=models.ForeignKey(blank=True, help_text='Company/provider associated with this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.company', verbose_name='Provider'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qualification_institution',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Qualification Institution'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='qualification_year',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Qualification Year'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Race/Ethnicity'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.ForeignKey(blank=True, help_text='Current state/region of residence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='localization.state', verbose_name='State/Region'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, help_text='Unique student identifier', max_length=50, null=True, unique=True, verbose_name='Student ID'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_status',
            field=models.CharField(choices=[('provisional', 'Provisional'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out'), ('rejected', 'Rejected')], default='provisional', max_length=30, verbose_name='Student Status'),
        ),
        migrations.AlterField(
            model_name='coursecartitem',
            name='training_type',
            field=models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry Training'), ('custom_selection', 'Custom Selection'), ('aicertscourse', 'AICerts Course'), ('course', 'Course'), ('offering', 'Industry Training')], max_length=20, verbose_name='Training Type'),
        ),
        migrations.AlterField(
            model_name='coursecatalogitem',
            name='training_type',
            field=models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry Training'), ('custom_selection', 'Custom Selection'), ('aicertscourse', 'AICerts Course'), ('course', 'Course'), ('offering', 'Industry Training')], max_length=20, verbose_name='Training Type'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='training_type',
            field=models.CharField(choices=[('masterclass', 'Masterclass'), ('learnership', 'Learnership'), ('industry_training', 'Industry Training'), ('custom_selection', 'Custom Selection'), ('aicertscourse', 'AICerts Course'), ('course', 'Course'), ('offering', 'Industry Training')], max_length=20, verbose_name='Training Type'),
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='students',
        ),
    ]
