# Generated by Django 4.2.16 on 2026-03-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learner_portal', '0007_studentprofile_city_studentprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Street Address'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Account Holder Name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Bank Account Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('savings', 'Savings'), ('cheque', 'Cheque/Current')], max_length=20, null=True, verbose_name='Bank Account Type'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_branch_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Branch Code'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_contact_relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Emergency Contact Relationship'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-Binary'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Number / Passport Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Money Number'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Mobile Money Provider'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code'),
        ),
    ]
