# Generated by Django 4.2.16 on 2026-04-30 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0012_add_smatpay_fee_fields'),
        ('learner_portal', '0008_add_personal_fields_to_student_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wishlists', to='localization.country', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Course Title'),
        ),
    ]
