# Generated by Django 5.2.10 on 2026-01-16 08:34

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiCertsCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('aicerts', 'AICERTs')], db_index=True, default='aicerts', max_length=50)),
                ('external_id', models.IntegerField(db_index=True, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('shortname', models.CharField(blank=True, max_length=100)),
                ('summary', models.TextField(blank=True)),
                ('category_name', models.CharField(blank=True, max_length=500)),
                ('certificate_badge_url', models.URLField(blank=True)),
                ('feature_image_url', models.URLField(blank=True)),
                ('lms_course_id', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('is_offered', models.BooleanField(default=False)),
                ('is_self_paced', models.BooleanField(default=False)),
                ('price_individual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_in_package', models.BooleanField(default=False)),
                ('package_name', models.CharField(blank=True, max_length=255)),
                ('price_package', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('last_synced', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_synced'],
            },
        ),
    ]
