# Generated by Django 5.2.10 on 2026-01-16 10:08

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicertscourse',
            options={'ordering': ['-last_synced'], 'verbose_name': 'AICERTs Raw Course', 'verbose_name_plural': 'AICERTs Raw Courses'},
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='description',
            field=models.TextField(blank=True, help_text='Full course description/summary from the API (HTML allowed)', null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.CharField(blank=True, help_text='Comma-separated category names from API', max_length=500),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_badge_url',
            field=models.URLField(blank=True, help_text='URL to the certificate badge image'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this record was first created in our DB'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='external_id',
            field=models.IntegerField(db_index=True, help_text='Unique ID from the AICERTs API', unique=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_url',
            field=models.URLField(blank=True, help_text='URL to the featured/course image'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='fullname',
            field=models.CharField(help_text='Full course title', max_length=255),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_in_package',
            field=models.BooleanField(default=False, help_text='Is this course part of a package/bundle?'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_offered',
            field=models.BooleanField(default=False, help_text='Is this course actively offered on the platform?'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_self_paced',
            field=models.BooleanField(default=False, help_text='Is the course self-paced?'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='last_synced',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this course was last synced from the API'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='lms_course_id',
            field=models.CharField(blank=True, help_text='Corresponding Moodle/LMS course ID (if synced)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='package_name',
            field=models.CharField(blank=True, help_text='Name of the package this course belongs to', max_length=255),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='price_individual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for individual enrollment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='price_package',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when purchased as part of a package', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='provider',
            field=models.CharField(choices=[('aicerts', 'AICERTs')], db_index=True, default='aicerts', help_text='The provider/platform this course comes from (currently only AICERTs)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete JSON response from the API (both list and detail endpoints)'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.CharField(blank=True, help_text='Short/abbreviated name (optional)', max_length=100),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='summary',
            field=models.TextField(blank=True, help_text='Short summary or excerpt (fallback if description is empty)'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last time this record was updated'),
        ),
        migrations.AddIndex(
            model_name='aicertscourse',
            index=models.Index(fields=['provider', 'external_id'], name='aicerts_cou_provide_dd0746_idx'),
        ),
        migrations.AddIndex(
            model_name='aicertscourse',
            index=models.Index(fields=['is_offered'], name='aicerts_cou_is_offe_7bfdef_idx'),
        ),
    ]
