# Generated by Django 4.2.16 on 2026-03-04 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0003_alter_aicertscourse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicertscourse',
            name='ai_tools',
            field=models.JSONField(blank=True, default=list, help_text='AI tools list from detail endpoint: [{name, image}]'),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='certificate_image_jpg_url',
            field=models.URLField(blank=True, help_text='JPG version of certificate badge via wsrv.nl — from list endpoint'),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='feature_image_jpg_url',
            field=models.URLField(blank=True, help_text='JPG version of feature image via wsrv.nl — from detail endpoint'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_badge_url',
            field=models.URLField(blank=True, help_text='URL to certificate badge image (SVG) — from list endpoint'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_url',
            field=models.URLField(blank=True, help_text='URL to featured course image (SVG) — from detail endpoint'),
        ),
    ]
