# Generated by Django 4.2.16 on 2026-03-16 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aicerts_courses', '0006_reclassify_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicertscourse',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to teach this AICERTS course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_aicerts_courses', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Instructor'),
        ),
    ]
