# Generated by Django 4.2.16 on 2026-04-20 19:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0007_aicertscourse_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicertscourse',
            options={'ordering': ['-last_synced'], 'verbose_name': 'AI Certs Course', 'verbose_name_plural': 'AI Certs Courses'},
        ),
        migrations.RemoveIndex(
            model_name='aicertscourse',
            name='aicerts_cou_provide_dd0746_idx',
        ),
        migrations.RemoveIndex(
            model_name='aicertscourse',
            name='aicerts_cou_is_offe_7bfdef_idx',
        ),
        migrations.RemoveIndex(
            model_name='aicertscourse',
            name='aicerts_cou_last_sy_56572e_idx',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='ai_tools',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='certificate_image_jpg_url',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='feature_image_jpg_url',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='aicertscourse',
            name='stream_type',
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_badge_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='external_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_in_package',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_offered',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_self_paced',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='last_synced',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='lms_course_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='package_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='price_individual',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='price_package',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='provider',
            field=models.CharField(default='aicerts', max_length=50),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
