# Generated by Django 4.2.16 on 2026-04-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0008_alter_aicertscourse_options_and_more'),
    ]

    operations = [
    ]
