# Generated by Django 4.2.16 on 2026-04-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0009_add_jpg_url_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicertscourse',
            name='certificate_image_jpg_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='feature_image_jpg_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='package_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
