# Generated by Django 4.2.16 on 2026-04-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0010_aicertscourse_certificate_image_jpg_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
