# Generated by Django 4.2.16 on 2026-04-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0011_alter_aicertscourse_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_badge_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='title',
            field=models.TextField(),
        ),
    ]
