# Generated by Django 4.2.16 on 2026-04-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0012_alter_aicertscourse_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='package_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
