# Generated by Django 4.2.16 on 2026-04-26 19:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aicerts_courses', '0013_alter_aicertscourse_package_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aicertscourse',
            options={'ordering': ['-last_synced'], 'verbose_name': 'AICERTs Course', 'verbose_name_plural': 'AICERTs Courses'},
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='ai_tools',
            field=models.JSONField(blank=True, default=list, help_text='AI tools list from detail endpoint: [{name, image}]'),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to teach this AICERTS course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_aicerts_courses', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Instructor'),
        ),
        migrations.AddField(
            model_name='aicertscourse',
            name='stream_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('professional', 'Professional')], db_index=True, default='professional', help_text='Stream type for pricing: Technical ($420) or Professional ($250)', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.CharField(blank=True, default='', help_text="Comma-separated category names (e.g. 'AI Healthcare,AI Professional')", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_badge_url',
            field=models.URLField(blank=True, default='', help_text='URL to certificate badge image (SVG) — from list endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_image_jpg_url',
            field=models.URLField(blank=True, default='', help_text='JPG version of certificate badge via wsrv.nl — from list endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Creation time in local DB'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='description',
            field=models.TextField(blank=True, help_text='Full course description (HTML allowed, from API)', null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='external_id',
            field=models.IntegerField(db_index=True, help_text='Unique course ID from AICERTs API', unique=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_jpg_url',
            field=models.URLField(blank=True, default='', help_text='JPG version of feature image via wsrv.nl — from detail endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_url',
            field=models.URLField(blank=True, default='', help_text='URL to featured course image (SVG) — from detail endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_in_package',
            field=models.BooleanField(default=False, help_text='Part of a package/bundle?'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_offered',
            field=models.BooleanField(default=False, help_text='Actively offered on the platform?'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='is_self_paced',
            field=models.BooleanField(default=False, help_text='Self-paced course?'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='last_synced',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Last sync time from AICERTs API'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='lms_course_id',
            field=models.CharField(blank=True, help_text='Moodle/LMS course ID (if synced)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='package_name',
            field=models.CharField(blank=True, default='', help_text='Package/bundle name', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='price_individual',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Individual enrollment price', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='price_package',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when bought in package', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='provider',
            field=models.CharField(choices=[('aicerts', 'AICERTs')], db_index=True, default='aicerts', help_text='Source platform (currently only AICERTs)', max_length=50),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='raw_data',
            field=models.JSONField(blank=True, default=dict, help_text='Complete JSON from list and detail endpoints (for new fields)'),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.CharField(blank=True, default='', help_text='Short/abbreviated name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Short excerpt/fallback summary'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='title',
            field=models.CharField(help_text="Full course title (maps to 'title' in API)", max_length=255),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Last update time'),
        ),
        migrations.AddIndex(
            model_name='aicertscourse',
            index=models.Index(fields=['provider', 'external_id'], name='aicerts_cou_provide_dd0746_idx'),
        ),
        migrations.AddIndex(
            model_name='aicertscourse',
            index=models.Index(fields=['is_offered'], name='aicerts_cou_is_offe_7bfdef_idx'),
        ),
        migrations.AddIndex(
            model_name='aicertscourse',
            index=models.Index(fields=['last_synced'], name='aicerts_cou_last_sy_56572e_idx'),
        ),
    ]
