# Generated by Django 4.2.16 on 2026-04-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicerts_courses', '0015_increase_char_limits_10000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aicertscourse',
            name='category_name',
            field=models.CharField(blank=True, help_text="Comma-separated category names (e.g. 'AI Healthcare,AI Professional')", max_length=1000000),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_badge_url',
            field=models.URLField(blank=True, default='', help_text='URL to certificate badge image (SVG) — from list endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='certificate_image_jpg_url',
            field=models.URLField(blank=True, default='', help_text='JPG version of certificate badge via wsrv.nl — from list endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='feature_image_url',
            field=models.URLField(blank=True, default='', help_text='URL to featured course image (SVG) — from detail endpoint'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='lms_course_id',
            field=models.CharField(blank=True, help_text='Moodle/LMS course ID (if synced)', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='package_name',
            field=models.CharField(blank=True, help_text='Package/bundle name', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='shortname',
            field=models.CharField(blank=True, help_text='Short/abbreviated name', max_length=10000),
        ),
        migrations.AlterField(
            model_name='aicertscourse',
            name='title',
            field=models.CharField(help_text="Full course title (maps to 'title' in API)", max_length=1000000),
        ),
    ]
