# Generated by Django 5.2.10 on 2026-01-23 13:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HrDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=191)),
                ('details', models.CharField(blank=True, max_length=191, null=True)),
                ('user', models.CharField(blank=True, max_length=191, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hr_departments',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official registered company name', max_length=255, verbose_name='Company Name')),
                ('registration_number', models.CharField(help_text='Official business registration number', max_length=100, unique=True, verbose_name='Company Registration Number')),
                ('tax_number', models.CharField(blank=True, help_text='Tax identification number', max_length=100, null=True, verbose_name='Tax/VAT Number')),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Company Email')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('website', models.URLField(blank=True, max_length=255, null=True, verbose_name='Company Website')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal/ZIP Code')),
                ('billing_contact_name', models.CharField(max_length=255, verbose_name='Billing Contact Name')),
                ('billing_contact_email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Billing Contact Email')),
                ('billing_contact_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Billing Contact Phone')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Industry/Sector')),
                ('company_size', models.CharField(blank=True, choices=[('1-10', '1-10 employees'), ('11-50', '11-50 employees'), ('51-200', '51-200 employees'), ('201-500', '201-500 employees'), ('501-1000', '501-1000 employees'), ('1000+', '1000+ employees')], max_length=20, null=True, verbose_name='Company Size')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Immediate Payment'), ('net_7', 'Net 7 Days'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days')], default='immediate', max_length=50, verbose_name='Payment Terms')),
                ('preferred_payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Preferred Payment Method')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, help_text='Company verification status by admin', verbose_name='Verified')),
                ('notes', models.TextField(blank=True, help_text='Internal notes visible only to admins', null=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_manager', models.ForeignKey(blank=True, limit_choices_to={'role_id': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Account Manager')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyLearner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, help_text="Company's internal employee ID", max_length=50, null=True, verbose_name='Employee ID')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='Department')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Job Title/Position')),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manager Name')),
                ('manager_email', models.EmailField(blank=True, max_length=255, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='Manager Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left At')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='organizations.company', verbose_name='Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Learner')),
            ],
            options={
                'verbose_name': 'Company Learner',
                'verbose_name_plural': 'Company Learners',
                'db_table': 'company_learners',
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True)),
                ('showroom_id', models.IntegerField(default=1)),
                ('warehouse_id', models.IntegerField(default=1)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=255, null=True)),
                ('current_address', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_address', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_salary', models.CharField(blank=True, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, max_length=150, null=True)),
                ('opening_balance', models.FloatField(default=0.0)),
                ('provisional_months', models.SmallIntegerField(default=0)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('leave_applicable_date', models.DateField(blank=True, null=True)),
                ('carry_forward', models.IntegerField(default=0)),
                ('is_carry_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organizations.hrdepartment')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'staffs',
            },
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='companies_name_c7a1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['registration_number'], name='companies_registr_49a0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['is_active', 'is_verified'], name='companies_is_acti_d98045_idx'),
        ),
        migrations.AddIndex(
            model_name='companylearner',
            index=models.Index(fields=['company', 'is_active'], name='company_lea_company_5ac6c5_idx'),
        ),
        migrations.AddIndex(
            model_name='companylearner',
            index=models.Index(fields=['user', 'is_active'], name='company_lea_user_id_b8aa1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companylearner',
            unique_together={('company', 'user')},
        ),
    ]
