# Generated by Django 4.2.16 on 2026-02-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_adminrole_unique_together_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companylearner',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companylearner',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companylearner',
            name='user',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyLearner',
        ),
    ]
