# Generated by Django 5.2.10 on 2026-01-16 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learnerships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnershipenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnership_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='learnershipphase',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='learnerships.learnershipprogramme'),
        ),
        migrations.AddField(
            model_name='learnershipenrollment',
            name='programme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='learnerships.learnershipprogramme'),
        ),
        migrations.AddField(
            model_name='learnershipschedule',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='learnerships.learnershipenrollment'),
        ),
        migrations.AddField(
            model_name='learnershipschedule',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='learnerships.learnershipphase'),
        ),
        migrations.AddField(
            model_name='phasecourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnerships.course'),
        ),
        migrations.AddField(
            model_name='phasecourse',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='learnerships.learnershipphase'),
        ),
        migrations.AlterUniqueTogether(
            name='learnershipenrollment',
            unique_together={('programme', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='phasecourse',
            unique_together={('phase', 'course')},
        ),
    ]
