# Generated by Django 4.2.16 on 2026-01-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnershipprogramme',
            name='title',
            field=models.CharField(help_text="Specific programme title (e.g., 'AI Developer / Machine Learning Engineer Learnership Programme')", max_length=255),
        ),
    ]
