# Generated by Django 4.2.16 on 2026-02-18 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0009_alter_city_options_state_alter_city_unique_together_and_more'),
        ('learnerships', '0003_alter_learnershipprogramme_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnershipschedule',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.state'),
        ),
        migrations.AlterField(
            model_name='learnershipprogramme',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learnershipschedule',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.country'),
        ),
        migrations.AlterField(
            model_name='learnershipschedule',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localization.city', verbose_name='City/Location'),
        ),
    ]
