# Generated by Django 4.2.16 on 2026-02-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0004_learnershipschedule_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnershipprogramme',
            name='accreditation_body',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='career_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='certificate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='current_participants',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='delivery_mode',
            field=models.CharField(default='hybrid', max_length=20),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='duration_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='enrollment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='entry_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='is_funded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='max_participants',
            field=models.PositiveIntegerField(default=35),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='nqf_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='provider',
            field=models.CharField(default='Hosi Academy', max_length=255),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='status',
            field=models.CharField(default='open', max_length=20),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='stipend_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='learnershipprogramme',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
