# Generated by Django 4.2.16 on 2026-02-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0005_learnershipprogramme_accreditation_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnershipprogramme',
            name='cost_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='learnershipprogramme',
            name='intake_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
