# Generated by Django 5.2.10 on 2026-03-03 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0007_learnershipphase_programme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='learnershipprogramme',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to teach this learnership programme', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_learnerships', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Instructor'),
        ),
    ]
