# Generated by Django 5.2.10 on 2026-03-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0010_learnership_enrollment_enhancement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnershipenrollment',
            options={'ordering': ['-enrolled_at'], 'verbose_name': 'Learnership Enrollment', 'verbose_name_plural': 'Learnership Enrollments'},
        ),
        migrations.RenameIndex(
            model_name='learnershipenrollment',
            new_name='learnership_status_1e6612_idx',
            old_name='learnership_status_enroll_idx',
        ),
        migrations.RenameIndex(
            model_name='learnershipenrollment',
            new_name='learnership_user_id_0f4a56_idx',
            old_name='learnership_user_status_idx',
        ),
        migrations.RenameIndex(
            model_name='learnershipenrollment',
            new_name='learnership_program_9229e6_idx',
            old_name='learnership_prog_status_idx',
        ),
        migrations.AlterField(
            model_name='learnershipenrollment',
            name='status',
            field=models.CharField(choices=[('provisional', 'Provisional (Payment Pending)'), ('payment_pending', 'Payment Pending (Cash Promise)'), ('payment_partial', 'Partial Payment Made (Debit Order Setup)'), ('payment_complete', 'Payment Complete'), ('pending_evidence', 'Pending Evidence Upload'), ('evidence_submitted', 'Evidence Submitted'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed (Payment + Prerequisites Met)'), ('rejected', 'Rejected (Prerequisites Not Met)'), ('refunded', 'Refunded'), ('expired', 'Expired'), ('active', 'Active (Learning in Progress)'), ('completed', 'Completed'), ('dropped_out', 'Dropped Out'), ('debit_order_pending', 'Debit Order Setup Pending')], default='provisional', help_text='Current enrollment status in the learnership pathway', max_length=20),
        ),
    ]
