# Generated by Django 4.2.16 on 2026-03-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0015_add_is_offered_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnershipenrollment',
            name='status',
            field=models.CharField(choices=[('provisional', 'Provisional (Payment Pending)'), ('payment_pending', 'Payment Pending (Cash Promise)'), ('payment_partial', 'Partial Payment Made (Debit Order Setup)'), ('payment_complete', 'Payment Complete'), ('pending_evidence', 'Pending Evidence Upload'), ('evidence_submitted', 'Evidence Submitted'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed (Payment + Prerequisites Met)'), ('rejected', 'Rejected (Prerequisites Not Met)'), ('refunded', 'Refunded'), ('expired', 'Expired')], default='provisional', help_text='Current enrollment status in the learnership pathway', max_length=20),
        ),
    ]
