# Generated by Django 4.2.16 on 2026-03-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0017_learnershipenrollment_db_alignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnershipprogramme',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
