# Generated by Django 4.2.16 on 2026-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnerships', '0018_alter_learnershipprogramme_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnershipprogramme',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
